//! Verify a *staged* Wasm-component plugin bundle before it is installed.
//!
//! A staging directory (produced by whatever fetched/unpacked the bundle —
//! not this module's concern) is expected to contain exactly:
//!
//! - `ryuzi-plugin.toml` — the [`PluginBundleManifest`] (TOML, hand-authored
//!   by the plugin publisher).
//! - the component file the manifest's `component` field names (e.g.
//!   `acme_connector.wasm`).
//! - `release.json` — the [`PluginRelease`] descriptor (JSON, generated by a
//!   registry) for this exact release.
//! - `plugin.sig` — a detached signature envelope over `release.json`'s raw
//!   staged bytes (see below). NOT part of the `ryuzi-plugin-sdk` bundle
//!   contract: the SDK crate is registry-agnostic and has no opinion on
//!   trust/signing, so the envelope format is defined here instead.
//!
//! # Signature protocol
//!
//! `plugin.sig` is UTF-8 JSON: `{ "key_id": "first-party", "signature":
//! "<base64 URL-safe-no-pad ed25519 signature>" }`.
//!
//! The signed message is the **exact raw bytes staged as `release.json`** —
//! not a parsed-then-re-serialized canonical form. This is deliberate: any
//! canonicalization step (key ordering, whitespace, number formatting) is
//! one more place where the signer's serializer and the verifier's
//! serializer could disagree and silently break every future signature, or
//! (worse) admit a byte-level mismatch that a re-canonicalizing verifier
//! would wrongly accept. Verifying byte-for-byte means whatever bytes were
//! signed are exactly the bytes that must be staged, full stop.
//!
//! `key_id` is looked up in a caller-supplied trusted-key map (key ID ->
//! Ed25519 verifying-key bytes) rather than a single compiled-in key, so
//! multiple signers (first-party, future third-party registries) can be
//! trusted without changing this module. An unrecognized `key_id` is
//! rejected before any cryptographic work.
//!
//! # Validation order
//!
//! 1. Parse `release.json` through [`PluginRelease::from_json`] and
//!    `ryuzi-plugin.toml` through [`PluginBundleManifest::from_toml`] — both
//!    already enforce their own structural contract (id shape, semver,
//!    non-empty fields, etc).
//! 2. Require the manifest and release describe the *same* plugin: matching
//!    `id` and exact (string-equal) `version`.
//! 3. Safely resolve the manifest's `component` filename against the
//!    staging root and require its canonical path stays inside the
//!    staging root's canonical path (rejects `../` traversal and symlink
//!    escapes; canonicalization also requires the component actually
//!    exists).
//! 4. Hash the component with SHA-256 and require the release's
//!    `component_sha256` is lowercase hex and matches exactly.
//! 5. Parse the `plugin.sig` envelope, reject an unrecognized `key_id`, and
//!    verify the signature against `release.json`'s exact raw staged bytes
//!    using `ed25519_dalek::VerifyingKey::verify_strict` (matching the
//!    `remote_catalog` precedent: `verify_strict` rejects low-order public
//!    keys and non-canonical signatures that non-strict `verify()` would
//!    admit).
//!
//! Deliberately out of scope: this module does not unpack archives, fetch
//! anything over the network, install/activate a bundle, or touch
//! Wasmtime. It only answers "is this staged directory a bundle I should
//! trust?".

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};
use ed25519_dalek::{Signature, VerifyingKey};
use ryuzi_plugin_sdk::{PluginBundleManifest, PluginRelease};
use serde::Deserialize;
use sha2::{Digest, Sha256};

/// The detached signature envelope staged as `plugin.sig`. Not part of the
/// `ryuzi-plugin-sdk` bundle contract (that crate is registry-agnostic) —
/// this module owns the trust/signing layer on top of it.
#[derive(Debug, Deserialize)]
struct SignatureEnvelope {
    key_id: String,
    signature: String,
}

/// A staged bundle that has passed every check in [`verify_bundle`]: its
/// manifest and release descriptor agree, its component's hash matches, and
/// its `release.json` carries a valid signature from a trusted key.
#[derive(Debug, Clone)]
pub struct VerifiedBundle {
    pub manifest: PluginBundleManifest,
    pub release: PluginRelease,
    pub staging_dir: PathBuf,
}

/// Verify a staged plugin bundle directory. See the module docs for the
/// exact file layout, signature protocol, and validation order.
///
/// `trusted_keys` maps a signer's key ID (as it appears in `plugin.sig`'s
/// `key_id` field, e.g. `"first-party"`) to that signer's Ed25519
/// verifying-key bytes. A `plugin.sig` naming a key ID absent from this map
/// is rejected before any cryptographic work is attempted.
pub fn verify_bundle(
    staging_dir: &Path,
    trusted_keys: &HashMap<String, [u8; 32]>,
) -> Result<VerifiedBundle> {
    // Step 1: parse the manifest and the raw release bytes.
    let manifest_toml = std::fs::read_to_string(staging_dir.join("ryuzi-plugin.toml"))
        .context("reading ryuzi-plugin.toml")?;
    let manifest =
        PluginBundleManifest::from_toml(&manifest_toml).context("parsing ryuzi-plugin.toml")?;

    let release_bytes =
        std::fs::read(staging_dir.join("release.json")).context("reading release.json")?;
    let release = PluginRelease::from_json(&release_bytes).context("parsing release.json")?;

    // Step 2: manifest and release must describe the same plugin release.
    if manifest.id != release.id {
        bail!(
            "bundle id mismatch: manifest id {:?} != release id {:?}",
            manifest.id,
            release.id
        );
    }
    if manifest.version != release.version {
        bail!(
            "bundle version mismatch: manifest version {:?} != release version {:?}",
            manifest.version,
            release.version
        );
    }

    // Step 3: safely resolve the component path and require it stays
    // within the staging root.
    let canonical_root = staging_dir
        .canonicalize()
        .with_context(|| format!("canonicalizing staging dir {}", staging_dir.display()))?;
    let component_path = staging_dir.join(&manifest.component);
    let canonical_component = component_path
        .canonicalize()
        .with_context(|| format!("canonicalizing component path {}", component_path.display()))?;
    if !canonical_component.starts_with(&canonical_root) {
        bail!(
            "component path {:?} escapes the staging directory",
            manifest.component
        );
    }

    // Step 4: hash the component and compare against the release's
    // declared checksum.
    let component_bytes = std::fs::read(&canonical_component)
        .with_context(|| format!("reading component {}", canonical_component.display()))?;
    let actual_hash = format!("{:x}", Sha256::digest(&component_bytes));
    let declared_hash = &release.component_sha256;
    if !declared_hash
        .chars()
        .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c))
    {
        bail!(
            "release component_sha256 must be lowercase hex, got {:?}",
            declared_hash
        );
    }
    if &actual_hash != declared_hash {
        bail!("component hash mismatch: expected {declared_hash}, got {actual_hash}");
    }

    // Step 5: parse and verify the signature envelope over the exact raw
    // staged release.json bytes.
    let sig_bytes = std::fs::read(staging_dir.join("plugin.sig")).context("reading plugin.sig")?;
    let envelope: SignatureEnvelope =
        serde_json::from_slice(&sig_bytes).context("parsing plugin.sig")?;

    let Some(pubkey) = trusted_keys.get(&envelope.key_id) else {
        bail!("untrusted signing key id: {:?}", envelope.key_id);
    };
    let verifying_key = VerifyingKey::from_bytes(pubkey)
        .with_context(|| format!("invalid trusted verifying key for {:?}", envelope.key_id))?;

    use base64::Engine as _;
    let signature_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(envelope.signature.as_bytes())
        .context("decoding plugin.sig signature as base64")?;
    let signature_arr: [u8; 64] = signature_bytes
        .as_slice()
        .try_into()
        .map_err(|_| anyhow::anyhow!("plugin.sig signature must be 64 bytes"))?;
    let signature = Signature::from_bytes(&signature_arr);

    verifying_key
        .verify_strict(&release_bytes, &signature)
        .map_err(|_| anyhow::anyhow!("plugin.sig signature verification failed"))?;

    Ok(VerifiedBundle {
        manifest,
        release,
        staging_dir: staging_dir.to_path_buf(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};
    use std::fs;

    const KEY_ID: &str = "first-party";

    fn signing_key() -> SigningKey {
        SigningKey::from_bytes(&[9u8; 32])
    }

    fn other_signing_key() -> SigningKey {
        SigningKey::from_bytes(&[3u8; 32])
    }

    fn trusted_keys() -> HashMap<String, [u8; 32]> {
        let mut map = HashMap::new();
        map.insert(KEY_ID.to_string(), signing_key().verifying_key().to_bytes());
        map
    }

    fn b64url(bytes: &[u8]) -> String {
        use base64::Engine as _;
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
    }

    fn manifest_toml(id: &str, version: &str) -> String {
        format!(
            r#"
id = "{id}"
name = "Acme Connector"
version = "{version}"
wit-api = "^0.1.0"
lifecycle = "singleton"
component = "acme_connector.wasm"
"#
        )
    }

    fn release_json(id: &str, version: &str, component_sha256: &str) -> Vec<u8> {
        format!(
            r#"{{
    "id": "{id}",
    "version": "{version}",
    "wit-api": "0.1.0",
    "component_url": "https://registry.example.com/{id}/{version}/acme_connector.wasm",
    "component_sha256": "{component_sha256}",
    "size_bytes": 1024,
    "published_at": "2026-07-12T00:00:00Z"
}}"#
        )
        .into_bytes()
    }

    /// Writes a fully valid, signed staging directory (manifest, component,
    /// release.json, plugin.sig) and returns its path plus the component
    /// bytes actually written (so tampering tests can diverge from it).
    fn write_valid_bundle(dir: &Path, key: &SigningKey, key_id: &str) {
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.join("acme_connector.wasm"), &component_bytes).unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(&component_bytes));
        fs::write(
            dir.join("ryuzi-plugin.toml"),
            manifest_toml("acme-connector", "0.1.0"),
        )
        .unwrap();

        let release_bytes = release_json("acme-connector", "0.1.0", &component_sha256);
        fs::write(dir.join("release.json"), &release_bytes).unwrap();

        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": key_id,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();
    }

    #[test]
    fn valid_bundle_verifies_successfully() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_bundle(dir.path(), &signing_key(), KEY_ID);

        let verified = verify_bundle(dir.path(), &trusted_keys())
            .expect("a correctly signed, matching bundle should verify");

        assert_eq!(verified.manifest.id, "acme-connector");
        assert_eq!(verified.release.id, "acme-connector");
        assert_eq!(
            verified.staging_dir.canonicalize().unwrap(),
            dir.path().canonicalize().unwrap()
        );
    }

    #[test]
    fn tampered_component_reports_hash_mismatch() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_bundle(dir.path(), &signing_key(), KEY_ID);

        // Mutate the component after the release/signature were computed
        // over the original bytes.
        fs::write(dir.path().join("acme_connector.wasm"), b"tampered bytes!!").unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("a tampered component must fail hash verification");
        assert!(
            err.to_string().contains("hash mismatch"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn unknown_signing_key_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        // Sign with a key whose id is not present in `trusted_keys()`.
        write_valid_bundle(dir.path(), &other_signing_key(), "some-other-signer");

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("a signature from an untrusted key id must be rejected");
        assert!(
            err.to_string().contains("untrusted signing key"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn id_mismatch_between_manifest_and_release_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.path().join("acme_connector.wasm"), &component_bytes).unwrap();
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            manifest_toml("acme-connector", "0.1.0"),
        )
        .unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(&component_bytes));
        // Different id in the release than in the manifest.
        let release_bytes = release_json("other-connector", "0.1.0", &component_sha256);
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("mismatched manifest/release ids must be rejected");
        assert!(
            err.to_string().contains("id mismatch"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn version_mismatch_between_manifest_and_release_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.path().join("acme_connector.wasm"), &component_bytes).unwrap();
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            manifest_toml("acme-connector", "0.1.0"),
        )
        .unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(&component_bytes));
        // Different (but still valid semver) version in the release.
        let release_bytes = release_json("acme-connector", "0.2.0", &component_sha256);
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("mismatched manifest/release versions must be rejected");
        assert!(
            err.to_string().contains("version mismatch"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn component_path_traversal_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        // A secret file living OUTSIDE the staging dir that a `../` component
        // reference would try to reach.
        let parent = dir.path().parent().unwrap().to_path_buf();
        let outside_name = format!("ryuzi-bundle-traversal-target-{}.wasm", std::process::id());
        let outside_path = parent.join(&outside_name);
        fs::write(&outside_path, b"outside bytes").unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(b"outside bytes".as_slice()));
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            format!(
                r#"
id = "acme-connector"
name = "Acme Connector"
version = "0.1.0"
wit-api = "^0.1.0"
lifecycle = "singleton"
component = "../{outside_name}"
"#
            ),
        )
        .unwrap();

        let release_bytes = release_json("acme-connector", "0.1.0", &component_sha256);
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let result = verify_bundle(dir.path(), &trusted_keys());
        fs::remove_file(&outside_path).ok();
        let err = result.expect_err("a component path escaping the staging dir must be rejected");
        assert!(
            err.to_string().contains("escapes the staging directory"),
            "unexpected error: {err}"
        );
    }
}
