//! Verify a *staged* Wasm-component plugin bundle before it is installed.
//!
//! A staging directory (produced by whatever fetched/unpacked the bundle —
//! not this module's concern) is expected to contain exactly:
//!
//! - `ryuzi-plugin.toml` — the [`PluginBundleManifest`] (TOML, hand-authored
//!   by the plugin publisher).
//! - the component file the manifest's `component` field names (e.g.
//!   `acme_connector.wasm`).
//! - `release.json` — the [`PluginRelease`] descriptor (JSON, generated by a
//!   registry) for this exact release.
//! - `plugin.sig` — a detached signature envelope over `release.json`'s raw
//!   staged bytes (see below). NOT part of the `ryuzi-plugin-sdk` bundle
//!   contract: the SDK crate is registry-agnostic and has no opinion on
//!   trust/signing, so the envelope format is defined here instead.
//!
//! # Signature protocol
//!
//! `plugin.sig` is UTF-8 JSON: `{ "key_id": "first-party", "signature":
//! "<base64 URL-safe-no-pad ed25519 signature>" }`.
//!
//! The signed message is the **exact raw bytes staged as `release.json`** —
//! not a parsed-then-re-serialized canonical form. This is deliberate: any
//! canonicalization step (key ordering, whitespace, number formatting) is
//! one more place where the signer's serializer and the verifier's
//! serializer could disagree and silently break every future signature, or
//! (worse) admit a byte-level mismatch that a re-canonicalizing verifier
//! would wrongly accept. Verifying byte-for-byte means whatever bytes were
//! signed are exactly the bytes that must be staged, full stop.
//!
//! `key_id` is looked up in a caller-supplied trusted-key map (key ID ->
//! Ed25519 verifying-key bytes) rather than a single compiled-in key, so
//! multiple signers (first-party, future third-party registries) can be
//! trusted without changing this module. An unrecognized `key_id` is
//! rejected before any cryptographic work.
//!
//! # Validation order
//!
//! 1. Parse `release.json` through [`PluginRelease::from_json`] and
//!    `ryuzi-plugin.toml` through [`PluginBundleManifest::from_toml`] — both
//!    already enforce their own structural contract (id shape, semver,
//!    non-empty fields, etc).
//! 2. Require the manifest and release describe the *same* plugin: matching
//!    `id` and exact (string-equal) `version`.
//! 3. Safely resolve the manifest's `component` filename against the
//!    staging root and require its canonical path stays inside the
//!    staging root's canonical path (rejects `../` traversal and symlink
//!    escapes; canonicalization also requires the component actually
//!    exists).
//! 4. Hash the component with SHA-256 and require the release's
//!    `component_sha256` is exactly 64 lowercase hex characters and matches
//!    exactly.
//! 5. Parse the `plugin.sig` envelope, reject an unrecognized `key_id`, and
//!    verify the signature against `release.json`'s exact raw staged bytes
//!    using `ed25519_dalek::VerifyingKey::verify_strict` (matching the
//!    `remote_catalog` precedent: `verify_strict` rejects low-order public
//!    keys and non-canonical signatures that non-strict `verify()` would
//!    admit).
//!
//! Deliberately out of scope: this module does not unpack archives, fetch
//! anything over the network, install/activate a bundle, or touch
//! Wasmtime. It only answers "is this staged directory a bundle I should
//! trust?".

use std::collections::HashMap;
use std::path::{Path, PathBuf};
#[cfg(test)]
use std::sync::atomic::{AtomicBool, Ordering};

use anyhow::{bail, Context, Result};
use ed25519_dalek::{Signature, VerifyingKey};
use ryuzi_plugin_sdk::{PluginBundleManifest, PluginRelease};
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::store::{ComponentPluginReleaseRecord, Store};

/// The detached signature envelope staged as `plugin.sig`. Not part of the
/// `ryuzi-plugin-sdk` bundle contract (that crate is registry-agnostic) —
/// this module owns the trust/signing layer on top of it.
#[derive(Debug, Deserialize)]
struct SignatureEnvelope {
    key_id: String,
    signature: String,
}

/// A staged bundle that has passed every check in [`verify_bundle`]: its
/// manifest and release descriptor agree, its component's hash matches, and
/// its `release.json` carries a valid signature from a trusted key.
#[derive(Debug, Clone)]
pub struct VerifiedBundle {
    pub manifest: PluginBundleManifest,
    pub release: PluginRelease,
    pub signing_key_id: String,
    pub staging_dir: PathBuf,
}

/// Verify a staged plugin bundle directory. See the module docs for the
/// exact file layout, signature protocol, and validation order.
///
/// `trusted_keys` maps a signer's key ID (as it appears in `plugin.sig`'s
/// `key_id` field, e.g. `"first-party"`) to that signer's Ed25519
/// verifying-key bytes. A `plugin.sig` naming a key ID absent from this map
/// is rejected before any cryptographic work is attempted.
pub fn verify_bundle(
    staging_dir: &Path,
    trusted_keys: &HashMap<String, [u8; 32]>,
) -> Result<VerifiedBundle> {
    // Step 1: parse the manifest and the raw release bytes.
    let manifest_toml = std::fs::read_to_string(staging_dir.join("ryuzi-plugin.toml"))
        .context("reading ryuzi-plugin.toml")?;
    let manifest =
        PluginBundleManifest::from_toml(&manifest_toml).context("parsing ryuzi-plugin.toml")?;

    let release_bytes =
        std::fs::read(staging_dir.join("release.json")).context("reading release.json")?;
    let release = PluginRelease::from_json(&release_bytes).context("parsing release.json")?;

    // Step 2: manifest and release must describe the same plugin release.
    if manifest.id != release.id {
        bail!(
            "bundle id mismatch: manifest id {:?} != release id {:?}",
            manifest.id,
            release.id
        );
    }
    if manifest.version != release.version {
        bail!(
            "bundle version mismatch: manifest version {:?} != release version {:?}",
            manifest.version,
            release.version
        );
    }

    // Step 3: safely resolve the component path and require it stays
    // within the staging root.
    let canonical_root = staging_dir
        .canonicalize()
        .with_context(|| format!("canonicalizing staging dir {}", staging_dir.display()))?;
    let component_path = staging_dir.join(&manifest.component);
    let canonical_component = component_path
        .canonicalize()
        .with_context(|| format!("canonicalizing component path {}", component_path.display()))?;
    if !canonical_component.starts_with(&canonical_root) {
        bail!(
            "component path {:?} escapes the staging directory",
            manifest.component
        );
    }

    // Step 4: hash the component and compare against the release's
    // declared checksum.
    let component_bytes = std::fs::read(&canonical_component)
        .with_context(|| format!("reading component {}", canonical_component.display()))?;
    let actual_hash = format!("{:x}", Sha256::digest(&component_bytes));
    let declared_hash = &release.component_sha256;
    if declared_hash.len() != 64
        || !declared_hash
            .chars()
            .all(|c| c.is_ascii_digit() || ('a'..='f').contains(&c))
    {
        bail!(
            "release component_sha256 is malformed: expected exactly 64 lowercase hex characters, got {:?}",
            declared_hash
        );
    }
    if &actual_hash != declared_hash {
        bail!("component hash mismatch: expected {declared_hash}, got {actual_hash}");
    }

    // Step 5: parse and verify the signature envelope over the exact raw
    // staged release.json bytes.
    let sig_bytes = std::fs::read(staging_dir.join("plugin.sig")).context("reading plugin.sig")?;
    let envelope: SignatureEnvelope =
        serde_json::from_slice(&sig_bytes).context("parsing plugin.sig")?;

    let Some(pubkey) = trusted_keys.get(&envelope.key_id) else {
        bail!("untrusted signing key id: {:?}", envelope.key_id);
    };
    let verifying_key = VerifyingKey::from_bytes(pubkey)
        .with_context(|| format!("invalid trusted verifying key for {:?}", envelope.key_id))?;

    use base64::Engine as _;
    let signature_bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(envelope.signature.as_bytes())
        .context("decoding plugin.sig signature as base64")?;
    let signature_arr: [u8; 64] = signature_bytes
        .as_slice()
        .try_into()
        .map_err(|_| anyhow::anyhow!("plugin.sig signature must be 64 bytes"))?;
    let signature = Signature::from_bytes(&signature_arr);

    verifying_key
        .verify_strict(&release_bytes, &signature)
        .map_err(|_| anyhow::anyhow!("plugin.sig signature verification failed"))?;

    Ok(VerifiedBundle {
        manifest,
        release,
        signing_key_id: envelope.key_id,
        staging_dir: staging_dir.to_path_buf(),
    })
}

/// Installed, verified bundle metadata resolved from an active pointer and the
/// matching release ledger row. No component code is loaded or executed.
#[derive(Debug, Clone)]
pub struct InstalledBundle {
    pub manifest: PluginBundleManifest,
    pub release: PluginRelease,
    pub release_record: ComponentPluginReleaseRecord,
    pub root: PathBuf,
    pub component_path: PathBuf,
}

/// Root used by the component-bundle installer for the current user.
pub fn installed_bundle_root() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(std::env::temp_dir)
        .join("ryuzi")
        .join("plugins")
}

/// Moves verified staging directories into their versioned location and then
/// atomically changes the per-plugin `current` pointer. The pointer is a text
/// file rather than a symlink so it behaves consistently across platforms.
pub struct ComponentBundleInstaller {
    root: PathBuf,
    store: Store,
    #[cfg(test)]
    fail_before_pointer: AtomicBool,
    #[cfg(test)]
    fail_after_pointer_replacement: AtomicBool,
}

impl ComponentBundleInstaller {
    pub fn new(root: PathBuf, store: Store) -> Self {
        Self {
            root,
            store,
            #[cfg(test)]
            fail_before_pointer: AtomicBool::new(false),
            #[cfg(test)]
            fail_after_pointer_replacement: AtomicBool::new(false),
        }
    }

    /// Test seam for exercising the pre-pointer failure boundary.
    #[cfg(test)]
    pub(crate) fn fail_before_pointer_replacement(&self) {
        self.fail_before_pointer.store(true, Ordering::SeqCst);
    }

    /// Test seam for exercising an activation failure after the pointer changes.
    #[cfg(test)]
    pub(crate) fn fail_after_pointer_replacement(&self) {
        self.fail_after_pointer_replacement
            .store(true, Ordering::SeqCst);
    }

    pub async fn install_verified(
        &self,
        bundle: VerifiedBundle,
    ) -> Result<ComponentPluginReleaseRecord> {
        let plugin_root = self.root.join(&bundle.release.id);
        let version_root = plugin_root.join(&bundle.release.version);
        std::fs::create_dir_all(&plugin_root)?;
        if version_root.exists() {
            bail!(
                "component release destination already exists: {}",
                version_root.display()
            );
        }
        std::fs::rename(&bundle.staging_dir, &version_root)
            .with_context(|| format!("moving verified bundle into {}", version_root.display()))?;

        let pointer = plugin_root.join("current");
        let previous = std::fs::read_to_string(&pointer).ok();
        #[cfg(test)]
        if self.fail_before_pointer.swap(false, Ordering::SeqCst) {
            let _ = std::fs::remove_dir_all(&version_root);
            bail!("injected failure before active pointer replacement");
        }
        if let Err(error) = write_atomic(&pointer, bundle.release.version.as_bytes()) {
            return Err(match std::fs::remove_dir_all(&version_root) {
                Ok(()) => error.context(format!(
                    "writing active bundle pointer {}",
                    pointer.display()
                )),
                Err(cleanup_error) => anyhow::anyhow!(
                    "writing active bundle pointer {} failed: {error}; removing moved bundle {} failed: {cleanup_error}",
                    pointer.display(),
                    version_root.display(),
                ),
            });
        }

        let record = ComponentPluginReleaseRecord {
            plugin_id: bundle.release.id.clone(),
            version: bundle.release.version.clone(),
            source_url: bundle.release.component_url.clone(),
            sha256: bundle.release.component_sha256.clone(),
            signing_key_id: bundle.signing_key_id.clone(),
            installed_at: crate::paths::now_ms(),
            active: false,
            revoked: false,
            revocation_reason: None,
        };
        let result = async {
            #[cfg(test)]
            if self
                .fail_after_pointer_replacement
                .swap(false, Ordering::SeqCst)
            {
                bail!("injected failure after active pointer replacement");
            }
            self.store.upsert_component_release(&record).await?;
            self.store
                .set_active_component_release(&record.plugin_id, &record.version)
                .await?;
            Ok::<_, anyhow::Error>(())
        }
        .await;
        if let Err(error) = result {
            return Err(cleanup_failed_activation(
                &pointer,
                previous.as_deref(),
                &version_root,
                error,
            ));
        }
        Ok(ComponentPluginReleaseRecord {
            active: true,
            ..record
        })
    }
}

fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    crate::agents::transaction::atomic_write(path, bytes)
}

fn restore_pointer(path: &Path, previous: Option<&str>) -> Result<()> {
    match previous {
        Some(value) => write_atomic(path, value.as_bytes()),
        None => match std::fs::remove_file(path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error.into()),
        },
    }
}

/// Rolls back a bundle activation that failed after the version directory was
/// moved into place and the active pointer was rewritten: restores the
/// pointer to its previous value (or removes it if there was none) and
/// removes the just-moved version directory, since it was freshly renamed by
/// this invocation and never became the active, ledgered release. Never
/// touches any other version directory. Returns an error that preserves
/// `activation_error` and appends any pointer-restore and/or version-removal
/// failures; if cleanup fully succeeds, returns `activation_error` unchanged.
fn cleanup_failed_activation(
    pointer: &Path,
    previous: Option<&str>,
    version_root: &Path,
    activation_error: anyhow::Error,
) -> anyhow::Error {
    let pointer_result = restore_pointer(pointer, previous);
    let removal_result = std::fs::remove_dir_all(version_root);

    match (pointer_result, removal_result) {
        (Ok(()), Ok(())) => activation_error,
        (Err(pointer_error), Ok(())) => anyhow::anyhow!(
            "activation failed: {activation_error}; restoring active bundle pointer {} failed: {pointer_error}",
            pointer.display()
        ),
        (Ok(()), Err(removal_error)) => anyhow::anyhow!(
            "activation failed: {activation_error}; removing moved bundle {} failed: {removal_error}",
            version_root.display()
        ),
        (Err(pointer_error), Err(removal_error)) => anyhow::anyhow!(
            "activation failed: {activation_error}; restoring active bundle pointer {} failed: {pointer_error}; removing moved bundle {} failed: {removal_error}",
            pointer.display(),
            version_root.display()
        ),
    }
}

/// Discover only bundles whose pointer, release ledger row, and on-disk
/// metadata agree. Invalid entries are rejected rather than guessed.
pub async fn load_active_bundles(root: &Path, store: &Store) -> Result<Vec<InstalledBundle>> {
    let canonical_root = root
        .canonicalize()
        .with_context(|| format!("canonicalizing bundle root {}", root.display()))?;
    let mut found = Vec::new();
    let entries = match std::fs::read_dir(&canonical_root) {
        Ok(entries) => entries,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(found),
        Err(error) => return Err(error.into()),
    };
    for entry in entries {
        let plugin_root = entry?.path();
        if !plugin_root.is_dir() {
            continue;
        }
        let canonical_plugin_root = plugin_root
            .canonicalize()
            .with_context(|| format!("canonicalizing plugin root {}", plugin_root.display()))?;
        if !canonical_plugin_root.starts_with(&canonical_root) {
            bail!(
                "plugin root escapes bundle root for {}",
                plugin_root.display()
            );
        }
        let plugin_id = plugin_root
            .file_name()
            .and_then(|n| n.to_str())
            .context("malformed plugin directory")?;
        let pointer = plugin_root.join("current");
        let version = std::fs::read_to_string(&pointer).context("reading active bundle pointer")?;
        let version = version.trim();
        if version.is_empty() || version.contains(['/', '\\']) || version == "." || version == ".."
        {
            bail!("malformed active pointer for {plugin_id}");
        }
        let version_root = plugin_root.join(version);
        if !version_root.is_dir() {
            bail!("active bundle path is missing for {plugin_id}");
        }
        let canonical_version_root = version_root.canonicalize().with_context(|| {
            format!(
                "canonicalizing active bundle path {}",
                version_root.display()
            )
        })?;
        if !canonical_version_root.starts_with(&canonical_plugin_root)
            || !canonical_version_root.starts_with(&canonical_root)
        {
            bail!("active bundle path escapes install root for {plugin_id}");
        }
        let record = store
            .active_component_release(plugin_id)
            .await?
            .with_context(|| format!("no active release for {plugin_id}"))?;
        if record.version != version || record.plugin_id != plugin_id || record.revoked {
            bail!("active pointer and release ledger mismatch for {plugin_id}");
        }
        let manifest = PluginBundleManifest::from_toml(&std::fs::read_to_string(
            canonical_version_root.join("ryuzi-plugin.toml"),
        )?)?;
        let release =
            PluginRelease::from_json(&std::fs::read(canonical_version_root.join("release.json"))?)?;
        if manifest.id != plugin_id
            || manifest.version != version
            || release.id != plugin_id
            || release.version != version
            || release.component_sha256 != record.sha256
        {
            bail!("active bundle metadata mismatch for {plugin_id}");
        }
        let component_path = canonical_version_root.join(&manifest.component);
        let canonical_component = component_path.canonicalize()?;
        if !canonical_component.starts_with(&canonical_version_root) {
            bail!("active component escapes bundle root");
        }
        let component_bytes = std::fs::read(&canonical_component).with_context(|| {
            format!("reading active component {}", canonical_component.display())
        })?;
        let actual_hash = format!("{:x}", Sha256::digest(&component_bytes));
        if actual_hash != release.component_sha256 {
            bail!(
                "active component hash mismatch: expected {}, got {}",
                release.component_sha256,
                actual_hash
            );
        }
        found.push(InstalledBundle {
            manifest,
            release,
            release_record: record,
            root: canonical_version_root,
            component_path: canonical_component,
        });
    }
    Ok(found)
}
#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};
    use std::fs;

    const KEY_ID: &str = "first-party";

    fn signing_key() -> SigningKey {
        SigningKey::from_bytes(&[9u8; 32])
    }

    fn other_signing_key() -> SigningKey {
        SigningKey::from_bytes(&[3u8; 32])
    }

    fn trusted_keys() -> HashMap<String, [u8; 32]> {
        let mut map = HashMap::new();
        map.insert(KEY_ID.to_string(), signing_key().verifying_key().to_bytes());
        map
    }

    fn b64url(bytes: &[u8]) -> String {
        use base64::Engine as _;
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes)
    }

    fn manifest_toml(id: &str, version: &str) -> String {
        format!(
            r#"
id = "{id}"
name = "Acme Connector"
version = "{version}"
wit-api = "^0.1.0"
lifecycle = "singleton"
component = "acme_connector.wasm"
"#
        )
    }

    fn release_json(id: &str, version: &str, component_sha256: &str) -> Vec<u8> {
        format!(
            r#"{{
    "id": "{id}",
    "version": "{version}",
    "wit-api": "0.1.0",
    "component_url": "https://registry.example.com/{id}/{version}/acme_connector.wasm",
    "component_sha256": "{component_sha256}",
    "size_bytes": 1024,
    "published_at": "2026-07-12T00:00:00Z"
}}"#
        )
        .into_bytes()
    }

    /// Writes a fully valid, signed staging directory (manifest, component,
    /// release.json, plugin.sig) and returns its path plus the component
    /// bytes actually written (so tampering tests can diverge from it).
    fn write_valid_bundle(dir: &Path, key: &SigningKey, key_id: &str) {
        write_valid_bundle_version(dir, key, key_id, "0.1.0");
    }

    fn write_valid_bundle_version(dir: &Path, key: &SigningKey, key_id: &str, version: &str) {
        write_valid_bundle_for_plugin(dir, key, key_id, "acme-connector", version);
    }

    fn write_valid_bundle_for_plugin(
        dir: &Path,
        key: &SigningKey,
        key_id: &str,
        plugin_id: &str,
        version: &str,
    ) {
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.join("acme_connector.wasm"), &component_bytes).unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(&component_bytes));
        fs::write(
            dir.join("ryuzi-plugin.toml"),
            manifest_toml(plugin_id, version),
        )
        .unwrap();

        let release_bytes = release_json(plugin_id, version, &component_sha256);
        fs::write(dir.join("release.json"), &release_bytes).unwrap();

        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": key_id,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();
    }

    fn component_release_record(version: &str, sha256: &str) -> ComponentPluginReleaseRecord {
        component_release_record_for_plugin("acme-connector", version, sha256)
    }

    fn component_release_record_for_plugin(
        plugin_id: &str,
        version: &str,
        sha256: &str,
    ) -> ComponentPluginReleaseRecord {
        ComponentPluginReleaseRecord {
            plugin_id: plugin_id.into(),
            version: version.into(),
            source_url: format!("https://registry.example.com/{version}"),
            sha256: sha256.into(),
            signing_key_id: KEY_ID.into(),
            installed_at: crate::paths::now_ms(),
            active: false,
            revoked: false,
            revocation_reason: None,
        }
    }

    fn valid_component_hash() -> String {
        format!("{:x}", Sha256::digest(b"fake wasm component bytes"))
    }

    #[cfg(unix)]
    fn create_directory_reparse_point(link: &Path, target: &Path) -> std::io::Result<()> {
        std::os::unix::fs::symlink(target, link)
    }

    #[cfg(windows)]
    fn create_directory_reparse_point(link: &Path, target: &Path) -> std::io::Result<()> {
        let status = std::process::Command::new("cmd")
            .args([
                "/C",
                "mklink",
                "/J",
                link.to_str().ok_or_else(|| {
                    std::io::Error::new(std::io::ErrorKind::InvalidInput, "non-UTF-8 link path")
                })?,
                target.to_str().ok_or_else(|| {
                    std::io::Error::new(std::io::ErrorKind::InvalidInput, "non-UTF-8 target path")
                })?,
            ])
            .status()?;
        if status.success() {
            Ok(())
        } else {
            Err(std::io::Error::other(format!(
                "mklink /J exited with {status}"
            )))
        }
    }

    #[tokio::test]
    async fn installing_second_valid_version_replaces_pointer_and_active_release() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = Store::open(db.path()).await.unwrap();
        let installer = ComponentBundleInstaller::new(root.path().to_path_buf(), store.clone());

        let first_staging = tempfile::tempdir().unwrap();
        write_valid_bundle_version(first_staging.path(), &signing_key(), KEY_ID, "0.1.0");
        installer
            .install_verified(verify_bundle(first_staging.path(), &trusted_keys()).unwrap())
            .await
            .unwrap();

        let second_staging = tempfile::tempdir().unwrap();
        write_valid_bundle_version(second_staging.path(), &signing_key(), KEY_ID, "0.1.1");
        installer
            .install_verified(verify_bundle(second_staging.path(), &trusted_keys()).unwrap())
            .await
            .unwrap();

        assert_eq!(
            fs::read_to_string(root.path().join("acme-connector/current")).unwrap(),
            "0.1.1"
        );
        assert_eq!(
            store
                .active_component_release("acme-connector")
                .await
                .unwrap()
                .unwrap()
                .version,
            "0.1.1"
        );
        let bundles = load_active_bundles(root.path(), &store).await.unwrap();
        assert_eq!(bundles.len(), 1);
        assert_eq!(bundles[0].release.version, "0.1.1");
    }

    #[tokio::test]
    async fn loader_rejects_pointer_and_database_active_version_mismatch() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = Store::open(db.path()).await.unwrap();
        let plugin_root = root.path().join("acme-connector");
        fs::create_dir_all(&plugin_root).unwrap();
        for version in ["0.1.0", "0.1.1"] {
            let version_root = plugin_root.join(version);
            fs::create_dir_all(&version_root).unwrap();
            write_valid_bundle_version(&version_root, &signing_key(), KEY_ID, version);
            store
                .upsert_component_release(&component_release_record(
                    version,
                    &valid_component_hash(),
                ))
                .await
                .unwrap();
        }
        store
            .set_active_component_release("acme-connector", "0.1.1")
            .await
            .unwrap();
        fs::write(plugin_root.join("current"), "0.1.0").unwrap();

        let err = load_active_bundles(root.path(), &store)
            .await
            .expect_err("the pointer and database must identify the same active version");
        assert!(
            err.to_string()
                .contains("pointer and release ledger mismatch"),
            "unexpected error: {err}"
        );
    }

    #[tokio::test]
    async fn loader_rejects_mutated_installed_component_hash() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = Store::open(db.path()).await.unwrap();
        let staging = tempfile::tempdir().unwrap();
        write_valid_bundle(staging.path(), &signing_key(), KEY_ID);
        let installer = ComponentBundleInstaller::new(root.path().to_path_buf(), store.clone());
        installer
            .install_verified(verify_bundle(staging.path(), &trusted_keys()).unwrap())
            .await
            .unwrap();

        fs::write(
            root.path().join("acme-connector/0.1.0/acme_connector.wasm"),
            b"mutated after installation",
        )
        .unwrap();

        let err = load_active_bundles(root.path(), &store)
            .await
            .expect_err("mutating an installed component must invalidate the active bundle");
        assert!(
            err.to_string().contains("hash mismatch"),
            "unexpected error: {err}"
        );
    }

    #[tokio::test]
    async fn failed_activation_after_pointer_restores_pointer_and_database_state() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = Store::open(db.path()).await.unwrap();
        let plugin_root = root.path().join("acme-connector");
        fs::create_dir_all(&plugin_root).unwrap();
        fs::write(plugin_root.join("current"), "0.0.1").unwrap();
        store
            .upsert_component_release(&component_release_record("0.0.1", "old"))
            .await
            .unwrap();
        store
            .set_active_component_release("acme-connector", "0.0.1")
            .await
            .unwrap();

        let staging = tempfile::tempdir().unwrap();
        write_valid_bundle(staging.path(), &signing_key(), KEY_ID);
        let installer = ComponentBundleInstaller::new(root.path().to_path_buf(), store.clone());
        installer.fail_after_pointer_replacement();

        let err = installer
            .install_verified(verify_bundle(staging.path(), &trusted_keys()).unwrap())
            .await
            .expect_err("injected activation failure must abort installation");
        assert!(
            err.to_string()
                .contains("injected failure after active pointer replacement"),
            "unexpected error: {err}"
        );
        assert_eq!(
            fs::read_to_string(plugin_root.join("current")).unwrap(),
            "0.0.1"
        );
        assert_eq!(
            store
                .active_component_release("acme-connector")
                .await
                .unwrap()
                .unwrap()
                .version,
            "0.0.1"
        );
    }

    #[tokio::test]
    async fn failed_activation_after_pointer_removes_version_and_retry_succeeds() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = Store::open(db.path()).await.unwrap();
        let installer = ComponentBundleInstaller::new(root.path().to_path_buf(), store.clone());

        let first_staging = tempfile::tempdir().unwrap();
        write_valid_bundle_version(first_staging.path(), &signing_key(), KEY_ID, "0.1.0");
        installer
            .install_verified(verify_bundle(first_staging.path(), &trusted_keys()).unwrap())
            .await
            .unwrap();

        let failing_staging = tempfile::tempdir().unwrap();
        write_valid_bundle_version(failing_staging.path(), &signing_key(), KEY_ID, "0.1.1");
        installer.fail_after_pointer_replacement();
        let verified = verify_bundle(failing_staging.path(), &trusted_keys()).unwrap();
        assert!(installer.install_verified(verified).await.is_err());

        let plugin_root = root.path().join("acme-connector");
        assert_eq!(
            fs::read_to_string(plugin_root.join("current")).unwrap(),
            "0.1.0"
        );
        assert_eq!(
            store
                .active_component_release("acme-connector")
                .await
                .unwrap()
                .unwrap()
                .version,
            "0.1.0"
        );
        assert!(!plugin_root.join("0.1.1").exists());

        let retry_staging = tempfile::tempdir().unwrap();
        write_valid_bundle_version(retry_staging.path(), &signing_key(), KEY_ID, "0.1.1");
        let verified = verify_bundle(retry_staging.path(), &trusted_keys()).unwrap();
        installer.install_verified(verified).await.unwrap();

        assert_eq!(
            fs::read_to_string(plugin_root.join("current")).unwrap(),
            "0.1.1"
        );
        assert_eq!(
            store
                .active_component_release("acme-connector")
                .await
                .unwrap()
                .unwrap()
                .version,
            "0.1.1"
        );
    }

    #[cfg(any(unix, windows))]
    #[tokio::test]
    async fn loader_rejects_version_reparse_point_outside_root() {
        let root = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let outside_version = outside.path().join("0.1.0");
        fs::create_dir_all(&outside_version).unwrap();
        write_valid_bundle_for_plugin(&outside_version, &signing_key(), KEY_ID, "github", "0.1.0");

        let plugin_root = root.path().join("github");
        fs::create_dir_all(&plugin_root).unwrap();
        fs::write(plugin_root.join("current"), "0.1.0").unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = Store::open(db.path()).await.unwrap();
        store
            .upsert_component_release(&component_release_record_for_plugin(
                "github",
                "0.1.0",
                &valid_component_hash(),
            ))
            .await
            .unwrap();
        store
            .set_active_component_release("github", "0.1.0")
            .await
            .unwrap();

        if let Err(error) =
            create_directory_reparse_point(&plugin_root.join("0.1.0"), &outside_version)
        {
            eprintln!("skipping reparse-point test: {error}");
            return;
        }

        let err = load_active_bundles(root.path(), &store)
            .await
            .expect_err("a version reparse point escaping the install root must be rejected");
        assert!(
            err.to_string().contains("outside") || err.to_string().contains("escapes"),
            "unexpected error: {err}"
        );
    }
    #[tokio::test]
    async fn installs_verified_bundle_and_discovers_it() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = crate::store::Store::open(db.path()).await.unwrap();
        let staging = tempfile::tempdir().unwrap();
        write_valid_bundle(staging.path(), &signing_key(), KEY_ID);
        let verified = verify_bundle(staging.path(), &trusted_keys()).unwrap();
        let installer = ComponentBundleInstaller::new(root.path().to_path_buf(), store.clone());
        let record = installer.install_verified(verified).await.unwrap();
        assert!(record.active);
        assert!(!staging.path().exists());
        assert_eq!(
            fs::read_to_string(root.path().join("acme-connector/current")).unwrap(),
            "0.1.0"
        );
        assert!(root
            .path()
            .join("acme-connector/0.1.0/release.json")
            .is_file());
        let bundles = load_active_bundles(root.path(), &store).await.unwrap();
        assert_eq!(bundles.len(), 1);
        assert_eq!(bundles[0].release.version, "0.1.0");
    }

    #[tokio::test]
    async fn failed_activation_preserves_previous_release() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = crate::store::Store::open(db.path()).await.unwrap();
        let plugin_root = root.path().join("acme-connector");
        fs::create_dir_all(&plugin_root).unwrap();
        fs::write(plugin_root.join("current"), "0.0.1").unwrap();
        let old = ComponentPluginReleaseRecord {
            plugin_id: "acme-connector".into(),
            version: "0.0.1".into(),
            source_url: "old".into(),
            sha256: "old".into(),
            signing_key_id: KEY_ID.into(),
            installed_at: 1,
            active: false,
            revoked: false,
            revocation_reason: None,
        };
        store.upsert_component_release(&old).await.unwrap();
        store
            .set_active_component_release("acme-connector", "0.0.1")
            .await
            .unwrap();
        let staging = tempfile::tempdir().unwrap();
        write_valid_bundle(staging.path(), &signing_key(), KEY_ID);
        let installer = ComponentBundleInstaller::new(root.path().to_path_buf(), store.clone());
        installer.fail_before_pointer_replacement();
        let verified = verify_bundle(staging.path(), &trusted_keys()).unwrap();
        assert!(installer.install_verified(verified).await.is_err());
        assert_eq!(
            fs::read_to_string(plugin_root.join("current")).unwrap(),
            "0.0.1"
        );
        assert_eq!(
            store
                .active_component_release("acme-connector")
                .await
                .unwrap()
                .unwrap()
                .version,
            "0.0.1"
        );
        assert!(!plugin_root.join("0.1.0").exists());
    }

    #[tokio::test]
    async fn loader_rejects_pointer_database_mismatch() {
        let root = tempfile::tempdir().unwrap();
        let db = tempfile::NamedTempFile::new().unwrap();
        let store = crate::store::Store::open(db.path()).await.unwrap();
        let plugin_root = root.path().join("acme-connector/0.1.0");
        fs::create_dir_all(&plugin_root).unwrap();
        fs::write(root.path().join("acme-connector/current"), "0.1.0").unwrap();
        let err = load_active_bundles(root.path(), &store).await.unwrap_err();
        assert!(err.to_string().contains("no active release"));
    }

    #[test]
    fn valid_bundle_verifies_successfully() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_bundle(dir.path(), &signing_key(), KEY_ID);

        let verified = verify_bundle(dir.path(), &trusted_keys())
            .expect("a correctly signed, matching bundle should verify");

        assert_eq!(verified.manifest.id, "acme-connector");
        assert_eq!(verified.release.id, "acme-connector");
        assert_eq!(
            verified.staging_dir.canonicalize().unwrap(),
            dir.path().canonicalize().unwrap()
        );
    }

    #[test]
    fn tampered_component_reports_hash_mismatch() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_bundle(dir.path(), &signing_key(), KEY_ID);

        // Mutate the component after the release/signature were computed
        // over the original bytes.
        fs::write(dir.path().join("acme_connector.wasm"), b"tampered bytes!!").unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("a tampered component must fail hash verification");
        assert!(
            err.to_string().contains("hash mismatch"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn signature_over_wrong_bytes_from_trusted_key_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_bundle(dir.path(), &signing_key(), KEY_ID);

        // Re-sign with the *trusted* key, but over different bytes than what
        // is actually staged as release.json. Everything else (manifest,
        // release, component hash, path, key id) stays valid, so this must
        // fail specifically inside `verify_strict`, not because of an
        // unknown key id or a component hash mismatch.
        let staged_release_bytes = fs::read(dir.path().join("release.json")).unwrap();
        let mut signed_over_bytes = staged_release_bytes.clone();
        signed_over_bytes.push(b'\n');
        assert_ne!(
            staged_release_bytes, signed_over_bytes,
            "signed bytes must differ from staged release.json bytes"
        );
        let signature = signing_key().sign(&signed_over_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys()).expect_err(
            "a signature computed over bytes other than the staged release.json must be rejected",
        );
        assert!(
            err.to_string().contains("signature verification failed"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn corrupted_signature_bytes_from_trusted_key_are_rejected() {
        let dir = tempfile::tempdir().unwrap();
        write_valid_bundle(dir.path(), &signing_key(), KEY_ID);

        // Corrupt the signature bytes themselves (still a valid trusted
        // `key_id`, still 64 bytes once decoded), so this must fail inside
        // `verify_strict`, not because of an unknown key id.
        let signature = signing_key().sign(&fs::read(dir.path().join("release.json")).unwrap());
        let mut corrupted = signature.to_bytes();
        corrupted[0] ^= 0xff;
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&corrupted),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("a corrupted signature from a trusted key id must be rejected");
        assert!(
            err.to_string().contains("signature verification failed"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn unknown_signing_key_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        // Sign with a key whose id is not present in `trusted_keys()`.
        write_valid_bundle(dir.path(), &other_signing_key(), "some-other-signer");

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("a signature from an untrusted key id must be rejected");
        assert!(
            err.to_string().contains("untrusted signing key"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn id_mismatch_between_manifest_and_release_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.path().join("acme_connector.wasm"), &component_bytes).unwrap();
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            manifest_toml("acme-connector", "0.1.0"),
        )
        .unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(&component_bytes));
        // Different id in the release than in the manifest.
        let release_bytes = release_json("other-connector", "0.1.0", &component_sha256);
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("mismatched manifest/release ids must be rejected");
        assert!(
            err.to_string().contains("id mismatch"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn version_mismatch_between_manifest_and_release_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.path().join("acme_connector.wasm"), &component_bytes).unwrap();
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            manifest_toml("acme-connector", "0.1.0"),
        )
        .unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(&component_bytes));
        // Different (but still valid semver) version in the release.
        let release_bytes = release_json("acme-connector", "0.2.0", &component_sha256);
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("mismatched manifest/release versions must be rejected");
        assert!(
            err.to_string().contains("version mismatch"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn component_path_traversal_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        // A secret file living OUTSIDE the staging dir that a `../` component
        // reference would try to reach.
        let parent = dir.path().parent().unwrap().to_path_buf();
        let outside_name = format!("ryuzi-bundle-traversal-target-{}.wasm", std::process::id());
        let outside_path = parent.join(&outside_name);
        fs::write(&outside_path, b"outside bytes").unwrap();

        let component_sha256 = format!("{:x}", Sha256::digest(b"outside bytes".as_slice()));
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            format!(
                r#"
id = "acme-connector"
name = "Acme Connector"
version = "0.1.0"
wit-api = "^0.1.0"
lifecycle = "singleton"
component = "../{outside_name}"
"#
            ),
        )
        .unwrap();

        let release_bytes = release_json("acme-connector", "0.1.0", &component_sha256);
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let result = verify_bundle(dir.path(), &trusted_keys());
        fs::remove_file(&outside_path).ok();
        let err = result.expect_err("a component path escaping the staging dir must be rejected");
        assert!(
            err.to_string().contains("escapes the staging directory"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn short_component_sha256_is_rejected_as_malformed() {
        let dir = tempfile::tempdir().unwrap();
        let component_bytes = b"fake wasm component bytes".to_vec();
        fs::write(dir.path().join("acme_connector.wasm"), &component_bytes).unwrap();
        fs::write(
            dir.path().join("ryuzi-plugin.toml"),
            manifest_toml("acme-connector", "0.1.0"),
        )
        .unwrap();

        // A short, all-lowercase-hex string: passes a naive "is every char
        // hex?" check but is not a 64-char SHA-256 digest.
        let release_bytes = release_json("acme-connector", "0.1.0", "ab");
        fs::write(dir.path().join("release.json"), &release_bytes).unwrap();

        let key = signing_key();
        let signature = key.sign(&release_bytes);
        let envelope = serde_json::json!({
            "key_id": KEY_ID,
            "signature": b64url(&signature.to_bytes()),
        });
        fs::write(
            dir.path().join("plugin.sig"),
            serde_json::to_vec(&envelope).unwrap(),
        )
        .unwrap();

        let err = verify_bundle(dir.path(), &trusted_keys())
            .expect_err("a component_sha256 that is not exactly 64 hex chars must be rejected");
        assert!(
            err.to_string().contains("malformed"),
            "unexpected error: {err}"
        );
        assert!(
            !err.to_string().contains("hash mismatch"),
            "malformed checksum must not be reported as a generic hash mismatch: {err}"
        );
    }
}
