
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<Project[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions(projectId: string | null) : Promise<Result<Session[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessages(sessionPk: string) : Promise<Result<Message[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_messages", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectProject(workdir: string, name: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_project", { workdir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cloneProject(url: string, destParent: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clone_project", { url, destParent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSession(projectId: string, prompt: string, options: ChatRequestOptions | null) : Promise<Result<Session, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_session", { projectId, prompt, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async continueSession(sessionPk: string, prompt: string, options: ChatRequestOptions | null) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_session", { sessionPk, prompt, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listToolPolicies() : Promise<Result<ToolPolicyRow[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tool_policies") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteToolPolicy(projectId: string, tool: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tool_policy", { projectId, tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(requestId: string, response: ApprovalResponse) : Promise<boolean> {
    return await TAURI_INVOKE("resolve_approval", { requestId, response });
},
async readFile(path: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Write pasted bytes into the attachments staging area and return the
 * absolute path — from there the file flows through the normal attachment
 * pipeline on send. Staging is wiped on app start (see lib.rs setup).
 */
async stageAttachment(name: string, dataBase64: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_attachment", { name, dataBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a media file as base64 for composer thumbnails (arbitrary user paths
 * sit outside the asset-protocol scope, so previews go through this instead).
 */
async readFileBase64(path: string) : Promise<Result<MediaFile, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_base64", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickDirectory() : Promise<string | null> {
    return await TAURI_INVOKE("pick_directory");
},
async pickFiles() : Promise<string[]> {
    return await TAURI_INVOKE("pick_files");
},
async backdropCapability() : Promise<BackdropCapability> {
    return await TAURI_INVOKE("backdrop_capability");
},
async getSetting(key: string) : Promise<Result<string | null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProject(projectId: string, model: string | null, permMode: PermMode, harness: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project", { projectId, model, permMode, harness }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setModelEffortPreference(key: ModelPreferenceKey, effort: string | null) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_effort_preference", { key, effort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async projectRuntimeInfo(projectId: string) : Promise<Result<ProjectRuntimeInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("project_runtime_info", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProjectRuntime(projectId: string, model: string | null, effort: string | null) : Promise<Result<ProjectRuntimeInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project_runtime", { projectId, model, effort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBranches(projectId: string) : Promise<Result<BranchList, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuntimes() : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runtimes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-probe every catalog agent (PATH + --version + npm latest + local model
 * list for ollama), persist the snapshot, and return the fresh assembly.
 */
async refreshRuntimes() : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_runtimes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRuntimeConfig(id: string, enabled: boolean, model: string | null, permMode: string, flags: string) : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_runtime_config", { id, enabled, model, permMode, flags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fire-and-forget npm update; progress streams via CoreEvent
 * RuntimeUpdateLog / RuntimeUpdateDone, then a refreshed snapshot matters —
 * the UI calls refreshRuntimes() on Done.
 */
async updateRuntime(id: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_runtime", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRuntimeTier(id: string, tierId: string, value: string | null, combo: boolean) : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_runtime_tier", { id, tierId, value, combo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultRuntime(id: string) : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_runtime", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runtimeConfigStatus(id: string) : Promise<Result<RuntimeConfigStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runtime_config_status", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Guard (spec §5): refuse to write configs that point at a dead endpoint —
 * the server must be running and at least one endpoint key must exist.
 */
async applyRuntimeConfig(id: string, mapping: RuntimeMappingArg) : Promise<Result<RuntimeConfigStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_runtime_config", { id, mapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetRuntimeConfig(id: string) : Promise<Result<RuntimeConfigStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_runtime_config", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGateways() : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_gateways") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Live probe: local telemetry, WSL detection, and SSH TCP reachability.
 */
async probeGateways() : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_gateways") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addGateway(name: string, host: string, port: number, username: string) : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_gateway", { name, host, port, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGateway(id: string) : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_gateway", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGateway(id: string, fsMode: string, paths: string[]) : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_gateway", { id, fsMode, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gatewayEvents(id: string) : Promise<Result<GatewayEventInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("gateway_events", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listJobs() : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_jobs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createJob(input: JobInput) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_job", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateJob(id: string, input: JobInput) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_job", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleJob(id: string, enabled: boolean) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_job", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteJob(id: string) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runJobNow(id: string) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_job_now", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview helper for the natural-language schedule editor.
 */
async parseNaturalSchedule(text: string) : Promise<string | null> {
    return await TAURI_INVOKE("parse_natural_schedule", { text });
},
async listApps() : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addApp(input: AddAppInput) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_app", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeApp(id: string) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_app", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeApp(id: string) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_app", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppScope(id: string, scope: string, scopeGateways: string[]) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_scope", { id, scope, scopeGateways }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppToolPerm(id: string, tool: string, perm: string) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_tool_perm", { id, tool, perm }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleAppAgent(id: string, agentId: string, allowed: boolean) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_app_agent", { id, agentId, allowed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDir(sessionPk: string, rel: string) : Promise<Result<DirEntryInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dir", { sessionPk, rel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Absolute root path of the session's working tree (for opening files).
 */
async sessionWorkdir(sessionPk: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_workdir", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the session's OWN worktree would lose on teardown — the archive flow
 * asks before discarding either kind of work. Sessions whose worktree is
 * gone (or isn't a repo, e.g. an emptied leftover dir) report clean —
 * deliberately NOT the project-workdir fallback: the main checkout's state
 * is the user's business, not the session's.
 */
async worktreeDirty(sessionPk: string) : Promise<Result<WorktreeState, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("worktree_dirty", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitDiff(sessionPk: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchFiles(projectId: string, query: string) : Promise<Result<string[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_files", { projectId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Revert one file in the session workdir to HEAD (Undo on a file-edit card).
 */
async revertFile(sessionPk: string, path: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revert_file", { sessionPk, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listOpenTargets() : Promise<OpenTarget[]> {
    return await TAURI_INVOKE("list_open_targets");
},
async openIn(sessionPk: string, targetId: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in", { sessionPk, targetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell in the session's worktree (or the project workdir).
 */
async termOpen(sessionPk: string, cols: number, rows: number) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_open", { sessionPk, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termInput(id: string, data: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_input", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termResize(id: string, cols: number, rows: number) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_resize", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termClose(id: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_close", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill every shell opened for a session — the archive/end flow runs this
 * BEFORE worktree teardown, or the shells' cwd handles block the directory
 * removal on Windows.
 */
async termCloseSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_close_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async systemAccentColor() : Promise<string | null> {
    return await TAURI_INVOKE("system_accent_color");
},
async endpointStatus() : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("endpoint_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startEndpoint() : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_endpoint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopEndpoint() : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_endpoint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist port + autostart; restart the server when it was running.
 */
async setEndpointConfig(port: number, autostart: boolean) : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_endpoint_config", { port, autostart }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEndpointKeys() : Promise<Result<EndpointKeyInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_endpoint_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEndpointKey(name: string) : Promise<Result<EndpointKeyInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_endpoint_key", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revokeEndpointKey(id: string) : Promise<Result<EndpointKeyInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revoke_endpoint_key", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectionUsage(connectionId: string, days: number) : Promise<Result<UsageSeries, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connection_usage", { connectionId, days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endpointUsage(days: number) : Promise<Result<UsageSeries, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("endpoint_usage", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderCatalog() : Promise<Result<CatalogEntry[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConnections() : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addConnection(provider: string, label: string, apiKey: string, baseUrl: string | null) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_connection", { provider, label, apiKey, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConnection(id: string, label: string, enabled: boolean, apiKey: string | null, baseUrl: string | null, models: string[], claudeCloaking: boolean | null) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_connection", { id, label, enabled, apiKey, baseUrl, models, claudeCloaking }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeConnection(id: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveConnection(id: string, dir: number) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_connection", { id, dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hit the upstream's model-list endpoint to distinguish bad credentials
 * (401/403) from network trouble, and persist the discovered model ids.
 */
async testConnection(id: string) : Promise<Result<TestResult, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async testConnectionModel(id: string, model: string) : Promise<Result<TestResult, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection_model", { id, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-fetch the live model list for every enabled connection in a vendor
 * family, persisting discoveries. Unlike the add/update-time best-effort
 * refresh, failures are returned to the UI instead of being swallowed.
 */
async refreshProviderModels(family: string) : Promise<Result<RefreshModelsResult[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_provider_models", { family }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persisted per-model probe verdicts for a vendor family — hydrates the
 * provider Models card so earlier Test All results show immediately.
 */
async listModelStatuses(family: string) : Promise<Result<ModelStatusInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_model_statuses", { family }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every persisted probe verdict, unfiltered — the family-scoped
 * `list_model_statuses` above stays for the provider Models card; this
 * variant feeds the app-wide picker filter.
 */
async listAllModelStatuses() : Promise<Result<ModelStatusEntry[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_all_model_statuses") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectionProviderQuota(id: string) : Promise<Result<ProviderQuotaInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connection_provider_quota", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetCodexCredit(id: string) : Promise<Result<CodexResetCreditResult, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_codex_credit", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listModelRoutes() : Promise<Result<ModelRouteInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_model_routes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveModelRoute(route: ModelRouteInfo) : Promise<Result<ModelRouteInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_model_route", { route }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModelRoute(id: string) : Promise<Result<ModelRouteInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model_route", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async providerAccountRoute(provider: string) : Promise<Result<ProviderAccountRouteInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("provider_account_route", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setProviderAccountRoute(provider: string, strategy: ModelRouteStrategy) : Promise<Result<ProviderAccountRouteInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_provider_account_route", { provider, strategy }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drive the full interactive OAuth flow: binds a loopback listener, opens
 * the provider's authorize URL in the system browser via
 * `tauri-plugin-opener`, and awaits the callback (up to 5 minutes) before
 * persisting the resulting connection.
 */
async connectOauth(provider: string, label: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_oauth", { provider, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reconnect an existing `needs_relogin` OAuth connection: drives the same
 * browser flow as [`connect_oauth`], but updates the connection in place
 * (same id/priority/label) instead of inserting a new row — otherwise the
 * stale, dead connection would keep shadowing the fresh one in
 * `route_model`'s `priority ASC` ordering.
 */
async reconnectOauth(connectionId: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconnect_oauth", { connectionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the manual (paste) OAuth fallback for environments where the
 * loopback listener can't receive the provider's redirect: opens the
 * authorize URL and hands back the PKCE material so the UI can show a paste
 * field, completed later via [`complete_oauth_manual`].
 */
async beginOauthManual(provider: string) : Promise<Result<ManualStartInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_oauth_manual", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeOauthManual(provider: string, label: string, verifier: string, state: string, pasted: string, redirectUri: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_oauth_manual", { provider, label, verifier, state, pasted, redirectUri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a `no_auth` connection for a Free-category provider — refuses any
 * other category (those need the api-key or OAuth flows above).
 */
async addFreeConnection(provider: string, label: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_free_connection", { provider, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The agents available for a project (built-ins plus discovered custom agents).
 */
async nativeAgents(projectId: string) : Promise<Result<AgentInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("native_agents", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The slash commands available for a project.
 */
async nativeCommands(projectId: string) : Promise<Result<CommandInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("native_commands", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * A session's current native todo list.
 */
async sessionTodos(sessionPk: string) : Promise<Result<TodoItem[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_todos", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSkills() : Promise<Result<InstalledSkillInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async installSkill(source: string) : Promise<Result<InstalledSkillPack, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_skill", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeSkill(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshSkill(id: string) : Promise<Result<InstalledSkillPack, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPlugins() : Promise<Result<PluginInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_plugins") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginDetail(id: string) : Promise<Result<PluginDetail, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_detail", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Same semantics as `ryuzi plugins enable/disable` — delegates to the
 * shared core helper so the two surfaces never drift.
 */
async setPluginEnabled(id: string, enabled: boolean) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_plugin_enabled", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validated write through `SettingsStore::set` — rejects unknown keys and
 * type-mismatched values the same way `ryuzi config set` does. Never
 * returns a value, so no secret can leak back through this command.
 */
async setPluginSetting(key: string, value: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_plugin_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async beginPluginOauth(pluginId: string) : Promise<Result<PluginOauthBeginResult, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_plugin_oauth", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completePluginOauth(pluginId: string, code: string, stateToken: string) : Promise<Result<PluginAuthInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_plugin_oauth", { pluginId, code, stateToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async disconnectPluginOauth(pluginId: string) : Promise<Result<PluginAuthInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("disconnect_plugin_oauth", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginModels(id: string) : Promise<Result<string[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_models", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The install wizard's entry point (spec 8-step resolution order). Steps
 * 1-6 live in `resolve_plugin_install`; this command adds step 7 (bind
 * 8976 — retried briefly — + background callback/exchange task, degrading
 * to `callback_mode: "manual"` only when the port is still taken after
 * the retries) and step 8 (emit `PluginOauthAuthorizeUrlMsg` + open the
 * browser), exactly like `begin_plugin_oauth` does for the detail view.
 */
async beginPluginInstall(pluginId: string) : Promise<Result<PluginInstallBeginResult, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_plugin_install", { pluginId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPluginOauthClientId(pluginId: string, clientId: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_plugin_oauth_client_id", { pluginId, clientId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the pending OAuth flow for this plugin, if any: shuts down the
 * callback listener and removes the flow-map entry. `state_token` narrows
 * to a specific flow when known; `None` cancels whatever is pending for
 * the id.
 */
async cancelPluginInstall(pluginId: string, stateToken: string | null) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_plugin_install", { pluginId, stateToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a session as a pretty JSON string.
 */
async exportSession(sessionPk: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a previously exported session JSON as a new archived session.
 */
async importSession(projectId: string, data: string) : Promise<Result<Session, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_session", { projectId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Render a session as a self-contained, shareable HTML document.
 */
async shareSession(sessionPk: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("share_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start Kiro's AWS SSO-OIDC device-code flow: registers a public client,
 * starts a device authorization, opens the browser to the verification URL,
 * and stashes the in-flight state under a fresh `flow_id` for
 * [`await_kiro_device_flow`] to poll. Does not touch the store — nothing is
 * persisted until the user completes the browser step.
 */
async startKiroDeviceFlow() : Promise<Result<DeviceFlowInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_kiro_device_flow") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Poll the token endpoint for a flow started by [`start_kiro_device_flow`]
 * until the user completes the browser step (or the code expires/is
 * denied), then persist the resulting `kiro`/`oauth` connection. The flow
 * state is consumed from [`FLOWS`] up front — a `flow_id` can only ever be
 * awaited once, success or failure.
 */
async awaitKiroDeviceFlow(label: string, flowId: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("await_kiro_device_flow", { label, flowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import Kiro OAuth tokens from an already-installed, logged-in Kiro IDE
 * (its AWS SSO token cache + optional client registration + profile.json),
 * so a connection can be created without running the device-code flow.
 * Validates the imported refresh token with one [`oauth::refresh::force_refresh`]
 * call (which mints a fresh access token) before persisting — a dead/expired
 * import token surfaces its error instead of a connection that can't route.
 */
async importKiroToken(label: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_kiro_token", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start an RFC 8628 device-authorization grant for a device-grant provider
 * (Qwen, GitHub Copilot): request a device code, open the verification URL,
 * and stash in-flight state under a fresh `flow_id` for `await_device_flow`.
 * Errors for providers that are not device-grant (e.g. `kiro`, which uses
 * `start_kiro_device_flow`).
 */
async startDeviceFlow(provider: string) : Promise<Result<DeviceFlowInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_device_flow", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Poll a device-grant flow started by `start_device_flow` until completion,
 * then persist the connection with `auth_type = "oauth"`. GitHub Copilot runs
 * the Copilot-token exchange (leg 2) before persisting; Qwen captures its
 * shard `resource_url`.
 */
async awaitDeviceFlow(provider: string, label: string, flowId: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("await_device_flow", { provider, label, flowId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
accentChangedMsg: AccentChangedMsg,
coreEventMsg: CoreEventMsg,
oauthAuthorizeUrlMsg: OauthAuthorizeUrlMsg,
pluginOauthAuthorizeUrlMsg: PluginOauthAuthorizeUrlMsg,
pluginOauthCompletedMsg: PluginOauthCompletedMsg,
termExitMsg: TermExitMsg,
termOutputMsg: TermOutputMsg
}>({
accentChangedMsg: "accent-changed-msg",
coreEventMsg: "core-event-msg",
oauthAuthorizeUrlMsg: "oauth-authorize-url-msg",
pluginOauthAuthorizeUrlMsg: "plugin-oauth-authorize-url-msg",
pluginOauthCompletedMsg: "plugin-oauth-completed-msg",
termExitMsg: "term-exit-msg",
termOutputMsg: "term-output-msg"
})

/** user-defined constants **/



/** user-defined types **/

export type AccentChangedMsg = { hex: string }
export type AddAppInput = { id: string | null; name: string; description: string; kind: string | null; 
/**
 * stdio | http
 */
transport: string; command: string | null; args: string[]; 
/**
 * KEY=VALUE pairs.
 */
env: string[]; url: string | null; version: string | null; publisher: string | null; color: string | null }
export type AgentAccessInfo = { agentId: string; allowed: boolean }
export type AgentInfo = { name: string; description: string; mode: string; builtin: boolean }
export type AppInfo = { id: string; name: string; kind: string; initial: string; color: string; desc: string; transport: string; command: string | null; args: string[]; url: string | null; scope: string; scopeGateways: string[]; status: string; statusDetail: string | null; version: string | null; publisher: string | null; authKind: string; authDetail: string | null; tools: ToolInfo[]; agentAccess: AgentAccessInfo[] }
/**
 * The user's decision on a tool-approval request. Mirrors ACP permission kinds.
 */
export type ApprovalDecision = "allowOnce" | "allowAlways" | "rejectOnce" | "rejectAlways" | "cancel"
/**
 * What a pending approval is asking the user for.
 */
export type ApprovalKind = 
/**
 * Permission to run one tool call.
 */
"tool" | 
/**
 * Review of an `exitplanmode` plan.
 */
"plan" | 
/**
 * An `askuserquestion` form.
 */
"question"
/**
 * The user's full reply to an approval request. `payload` carries
 * kind-specific data: `{"mode": "acceptEdits"|"default"}` or
 * `{"feedback": "…"}` for Plan, `{"answers": {question: [labels]}}`
 * for Question.
 */
export type ApprovalResponse = { decision: ApprovalDecision; scope: ApprovalScope | null; payload: JsonValue | null }
/**
 * Where an `AllowAlways`/`RejectAlways` decision is remembered.
 */
export type ApprovalScope = 
/**
 * In-memory for the current session only.
 */
"session" | 
/**
 * Persisted to the project's `tool_policies` row.
 */
"project"
export type BackdropCapability = "mica" | "vibrancy" | "none"
export type BranchList = { 
/**
 * Local branch names — current first, then alphabetical.
 */
branches: string[]; 
/**
 * Branch checked out in the project workdir; a short commit id when
 * HEAD is detached, "HEAD" when the repo has no commits yet.
 */
current: string; detached: boolean }
export type CatalogEntry = { id: string; name: string; 
/**
 * Vendor family id (a catalog id). Entries sharing a family render as one
 * provider card; the entry whose id == family is the display head.
 */
family: string; color: string; initial: string; category: string; format: string; requiresBaseUrl: boolean; models: string[]; freeTier: boolean; riskNotice: boolean; usesDeviceGrant: boolean }
export type ChatContextArg = { branch: string | null; voiceTranscript: string | null; references?: string[] }
export type ChatRequestOptions = { runtimeId: string | null; model: string | null; context: ChatContextArg | null; attachments?: string[]; 
/**
 * None => engine default (worktree ON, new engine-named branch from HEAD).
 */
git: GitOptions | null }
export type CmdError = { message: string }
export type CodexResetCreditInfo = { status: string; grantedAt: string | null; expiresAt: string | null }
export type CodexResetCreditResult = { reset: boolean; code: string | null; windowsReset: number; message: string | null; redeemRequestId: string | null }
export type CodexResetCreditsInfo = { availableCount: number; credits: CodexResetCreditInfo[] }
export type CommandInfo = { name: string; description: string; agent: string | null }
export type ConnectionInfo = { id: string; provider: string; providerName: string; color: string; initial: string; authType: string; label: string; priority: number; enabled: boolean; baseUrl: string | null; models: string[]; 
/**
 * e.g. "sk-…3fk9" — full key never leaves the backend after creation.
 */
keyMasked: string | null; 
/**
 * OAuth connections only: true once refresh has failed terminally and
 * the user needs to reconnect via the browser/paste flow again.
 */
needsRelogin: boolean; 
/**
 * Anthropic OAuth only: enable full Claude Code-style request cloaking.
 */
claudeCloaking: boolean }
/**
 * Public event broadcast to consumers (the Tauri layer re-emits these).
 */
export type CoreEvent = { kind: "sessionCreated"; session_pk: string; project_id: string } | { kind: "message"; session_pk: string; seq: number; role: string; block_type: string; payload: JsonValue; tool_call_id: string | null; status: string | null; tool_kind: string | null } | { kind: "result"; session_pk: string } | { kind: "approvalRequested"; session_pk: string; request_id: string; tool: string; summary: string; approval_kind: ApprovalKind; input: JsonValue } | { kind: "error"; session_pk: string; message: string } | 
/**
 * Out-of-band announcement (e.g. "update available") rendered to every
 * surface of a session.
 */
{ kind: "notice"; session_pk: string; text: string } | { kind: "sessionEnded"; session_pk: string } | 
/**
 * A scheduled job run started or finished (status: running|success|failed).
 */
{ kind: "jobRunChanged"; job_id: string; run_id: string; status: string } | 
/**
 * An orchestrated task changed status (todo|ready|running|done|failed|
 * cancelled; roots also decomposing|waiting|judging).
 */
{ kind: "orchTaskChanged"; task_id: string; root_id: string | null; status: string } | 
/**
 * A runtime npm install/update produced an output line.
 */
{ kind: "runtimeUpdateLog"; runtime_id: string; line: string } | 
/**
 * A runtime npm install/update finished (ok=false → message has detail).
 */
{ kind: "runtimeUpdateDone"; runtime_id: string; ok: boolean; message: string | null } | 
/**
 * Per-response context usage for a native session (drives the
 * "% context left" indicator).
 */
{ kind: "contextUsage"; session_pk: string; active_tokens: number; context_window: number; usable_window: number; percent_left: number; cache_read_tokens: number; output_tokens: number } | 
/**
 * The native runtime compacted a session's history
 * (trigger: pre_turn|mid_turn|manual).
 */
{ kind: "contextCompacted"; session_pk: string; trigger: string; before_tokens: number; after_tokens: number; window_number: number }
export type CoreEventMsg = { event: CoreEvent }
/**
 * Device-code flow info shown to the user while they complete the browser
 * step (Kiro): the short code to enter, the URL to visit, and the poll
 * cadence the frontend's `await_kiro_device_flow` call will honor.
 */
export type DeviceFlowInfo = { flowId: string; userCode: string; verificationUri: string; verificationUriComplete: string; expiresIn: number; interval: number }
export type DirEntryInfo = { name: string; dir: boolean }
export type EffectiveEffortSource = "project" | "routeCompatibility" | "configured" | "provider" | "none"
export type EndpointKeyInfo = { id: string; name: string; key: string; createdAt: number; lastUsedAt: number | null }
export type EndpointStatusInfo = { running: boolean; port: number; baseUrl: string; autostart: boolean; keychainStatus: KeychainStatus }
export type GatewayEventInfo = { at: number; level: string; text: string }
export type GatewayInfo = { id: string; name: string; badge: string; 
/**
 * local | wsl | ssh
 */
kind: string; detail: string; metaLine: string; 
/**
 * connected | offline
 */
status: string; latency: string | null; daemonVersion: string; uptime: string | null; lastSeenMs: number | null; resources: GatewayResourceInfo[]; fingerprint: string | null; fsMode: string; paths: string[] }
export type GatewayResourceInfo = { label: string; sub: string; pct: number }
/**
 * Per-start git controls from the composer (behavior matrix, workstream B).
 */
export type GitOptions = { useWorktree: boolean; createBranch: boolean; branchName: string | null; baseBranch: string | null }
export type InstalledSkillEntry = { id: string; name: string }
export type InstalledSkillInfo = { id: string; name: string; source: string; pluginId: string | null; installedAt: string; skillCount: number }
export type InstalledSkillPack = { id: string; name: string; source: string; pluginId: string | null; installedAt: string; skills: InstalledSkillEntry[] }
export type JobInfo = { id: string; name: string; cron: string; mode: string; natural: string; projectId: string; projectName: string; branch: string; agent: string; gateway: string; enabled: boolean; prompt: string; notifySuccess: boolean; notifyFail: boolean; nextRunMs: number | null; history: RunInfo[] }
export type JobInput = { name: string; mode: string; natural: string; cron: string; projectId: string; branch: string; agent: string; gateway: string; prompt: string; notifySuccess: boolean; notifyFail: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Where the process's master key actually came from. Surfaced to the UI
 * (via a later task's DTO mapping) so users know whether their secrets are
 * protected by the OS keychain or a weaker fallback.
 */
export type KeychainStatus = 
/**
 * Master key is stored in (and was read from, or freshly provisioned
 * into) the OS keychain.
 */
"ok" | 
/**
 * The OS keychain is unavailable (headless/locked/no D-Bus session), so
 * the master key lives in a permission-restricted file instead.
 */
"fileFallback" | 
/**
 * Neither the keychain nor the fallback file could be used reliably;
 * an ephemeral in-memory key is in play and secrets will not survive a
 * restart, or a previously stored key was corrupt and was replaced.
 */
"unavailable"
export type ManualStartInfo = { authorizeUrl: string; verifier: string; state: string; redirectUri: string }
export type MediaFile = { dataBase64: string; contentType: string | null }
/**
 * A persisted transcript entry. Forward-compatible with ACP session/update blocks.
 */
export type Message = { sessionPk: string; seq: number; role: string; blockType: string; payload: JsonValue; toolCallId: string | null; status: string | null; toolKind: string | null; createdAt: number }
export type ModelDefaultSource = "configured" | "provider" | "variesByTarget" | "none"
export type ModelPreferenceKey = { family: string; model: string }
export type ModelRouteInfo = { id: string; name: string; enabled: boolean; strategy: ModelRouteStrategy; targets: ModelRouteTarget[]; createdAt: number; updatedAt: number }
export type ModelRouteStrategy = "fallback" | "round-robin"
export type ModelRouteTarget = { 
/**
 * A family id (registry family head), e.g. "anthropic" — NOT a
 * connection id. The router expands this to every enabled account in
 * the family serving `model`, at request time.
 */
provider: string; model: string; 
/**
 * Compatibility-only storage for legacy Codex virtual model suffixes.
 * New route writes cannot edit this value directly.
 */
effort?: string | null }
/**
 * One persisted probe verdict row across ALL families — hydrates the
 * app-wide model-status store consumed by every model picker.
 */
export type ModelStatusEntry = { family: string; model: string; status: string; message: string; testedAt: number }
/**
 * One persisted probe verdict row for the provider Models card.
 */
export type ModelStatusInfo = { model: string; status: string; message: string; testedAt: number }
export type OauthAuthorizeUrlMsg = { provider: string; authorizeUrl: string }
export type OpenTarget = { id: string; name: string }
export type PermMode = "default" | "acceptEdits" | "bypassPermissions" | "plan"
export type PluginAuthInfo = { 
/**
 * `none` | `api-key` | `token` | `oauth`.
 */
kind: string; setting: string | null; env: string | null; helpUrl: string | null; 
/**
 * A persisted (non-empty) row exists for `setting`, OR `env` is set in
 * the process environment. Never reveals the value itself.
 */
configured: boolean; oauthConnectAvailable: boolean; oauthConnectError: string | null; oauthTokenStored: boolean; oauthReconnectRequired: boolean }
export type PluginDetail = { info: PluginInfo; auth: PluginAuthInfo | null; settings: PluginFieldInfo[]; mcp: PluginMcpInfo[]; models: string[]; homepage: string | null; publisher: string }
export type PluginFieldInfo = { key: string; label: string; help: string; secret: boolean; required: boolean; 
/**
 * A persisted (non-empty) row exists for `key`. Never the value itself.
 */
valueSet: boolean }
export type PluginInfo = { id: string; name: string; description: string; icon: string | null; categories: string[]; verified: boolean; experimental: boolean; enabled: boolean; 
/**
 * Same semantics as `PluginAuthInfo.configured` (oauth: token stored &&
 * !reconnect_required; else a persisted `auth.setting` row or `auth.env`
 * set). `false` when the manifest declares no `[auth]` block. On the
 * LIST payload (not just `plugin_detail`) because the Browse grid's
 * Install/Open split needs it — note this adds per-plugin store lookups
 * to list assembly.
 */
configured: boolean; 
/**
 * `builtin` | `catalog` | `skill-pack`.
 */
source: string; 
/**
 * Any of `provider` | `runtime` | `gateway` | `connector`.
 */
capabilities: string[] }
export type PluginInstallBeginResult = { 
/**
 * `none` | `api-key` | `token` | `oauth`.
 */
authKind: string; 
/**
 * `auth.env` is declared AND set in the environment.
 */
envVarPresent: boolean; envVarName: string | null; 
/**
 * Endpoints + client id resolved; the browser flow started.
 */
oauthAvailable: boolean; 
/**
 * OAuth brokered outside Cockpit (kind=oauth, no `auth.resource`, no
 * manifest `authorize_url` — google-workspace).
 */
oauthExternal: boolean; 
/**
 * oauth, endpoints may be known, but no client id and DCR not
 * applicable / failed.
 */
needsClientId: boolean; 
/**
 * This call performed a successful registration.
 */
dcrSucceeded: boolean; 
/**
 * `auto` (callback server bound) | `manual` (bind failed → paste).
 */
callbackMode: string; oauthBegin: PluginOauthBeginResult | null; 
/**
 * Discovery/DCR failure detail (shown on the manual client id form).
 */
dcrError: string | null }
export type PluginMcpInfo = { name: string; 
/**
 * `stdio` | `http`.
 */
transport: string; 
/**
 * The raw manifest string (command for stdio, url for http) — no
 * `${auth}` substitution, matching `ryuzi plugins info`'s output.
 */
commandOrUrl: string }
export type PluginOauthAuthorizeUrlMsg = { pluginId: string; authorizeUrl: string }
export type PluginOauthBeginResult = { stateToken: string; authorizeUrl: string; redirectUri: string }
/**
 * Emitted by `begin_plugin_install`'s background callback task when the
 * loopback OAuth flow finishes: `ok: true` after the token is stored;
 * `ok: false` (with `error`) on timeout, state mismatch, or exchange
 * failure — the flow entry survives failures so manual paste still works.
 */
export type PluginOauthCompletedMsg = { pluginId: string; ok: boolean; error: string | null }
export type Project = { projectId: string; name: string; workdir: string; source: string | null; harness: string; model: string | null; effort: string | null; permMode: PermMode; createdAt: number | null; 
/**
 * Computed at read time (`git2::Repository::open` probe on `workdir`) —
 * NOT a DB column. Self-corrects if the user later runs `git init`.
 */
isGit: boolean }
export type ProjectRuntimeInfo = { projectId: string; model: string | null; storedEffort: string | null; effectiveEffort: string | null; effectiveEffortLabel: string | null; effectiveSource: EffectiveEffortSource; storedEffortStatus: StoredEffortStatus; modelInfo: SelectableModelInfo | null }
export type ProviderAccountRouteInfo = { provider: string; strategy: ModelRouteStrategy }
export type ProviderQuotaInfo = { provider: string; plan: string | null; message: string | null; limitReached: boolean; reviewLimitReached: boolean; resetCredits: CodexResetCreditsInfo | null; quotas: QuotaWindowInfo[] }
export type QuotaWindowInfo = { label: string; used: number; total: number; remaining: number; usedPercentage: number; remainingPercentage: number; resetAt: string | null; unlimited: boolean }
export type ReasoningEffortOption = { value: string; label: string; description: string | null }
export type RefreshModelsResult = { connectionId: string; label: string; ok: boolean; message: string }
export type RunInfo = { id: string; status: string; startedAtMs: number; durationMs: number | null; addLines: number | null; delLines: number | null; note: string | null; error: string | null; sessionPk: string | null }
export type RuntimeConfigStatusInfo = { configPath: string; exists: boolean; configured: boolean; 
/**
 * False for runtimes without an F1 handler (gemini, ollama).
 */
supported: boolean }
export type RuntimeInfo = { id: string; name: string; color: string; initial: string; connection: string; binaryPath: string | null; installedVersion: string | null; latestVersion: string | null; npmPackage: string | null; models: string[]; selectableModels: SelectableModelInfo[]; enabled: boolean; model: string; permMode: string; flags: string; tiers: TierInfo[]; isDefault: boolean; 
/**
 * Whether Cockpit has a session harness for this agent today.
 */
runnable: boolean }
export type RuntimeMappingArg = { model: string; opus: string | null; sonnet: string | null; haiku: string | null; models: string[] }
export type SelectableModelInfo = { kind: SelectableModelKind; requestValue: string; displayName: string; preferenceKey: ModelPreferenceKey | null; supported: ReasoningEffortOption[]; configuredDefault: string | null; resolvedDefault: string | null; defaultSource: ModelDefaultSource }
export type SelectableModelKind = "concrete" | "namedRoute"
export type Session = { sessionPk: string; projectId: string; agentSessionId: string | null; worktreePath: string | null; branch: string | null; title: string | null; status: SessionStatus; startedBy: string | null; createdAt: number | null; lastActive: number | null; resumeAttempts: number; 
/**
 * True when the engine auto-generated the branch name (`harness/{short}`).
 * `end_session` deletes the branch ONLY when this is set; user-named and
 * pre-existing branches survive teardown.
 */
branchOwned: boolean }
export type SessionStatus = "idle" | "running" | "interrupted" | "ended"
export type StoredEffortStatus = "valid" | "unsupported" | "unknownMetadata"
export type TermExitMsg = { id: string }
export type TermOutputMsg = { id: string; 
/**
 * UTF-8 chunk (lossy) of PTY output.
 */
data: string }
export type TestResult = { 
/**
 * Legacy pass/fail, kept for existing call sites (connection-level
 * test, toasts). Always derived: `status == "valid"`.
 */
ok: boolean; 
/**
 * Tri-state probe verdict: "valid" | "invalid" | "unknown".
 */
status: string; message: string }
export type TierInfo = { id: string; label: string; value: string | null; combo: boolean }
export type TodoItem = { content: string; status: string }
export type ToolInfo = { name: string; desc: string; perm: string }
/**
 * One persisted "don't ask again" rule (Settings → Permissions).
 */
export type ToolPolicyRow = { projectId: string; tool: string; decision: string }
export type UsagePoint = { day: string; requests: number; inputTokens: number; outputTokens: number }
export type UsageSeries = { days: UsagePoint[]; todayRequests: number; todayInputTokens: number; todayOutputTokens: number }
export type WorktreeState = { 
/**
 * Uncommitted work (staged, unstaged, or untracked).
 */
dirty: boolean; 
/**
 * Commits reachable only from the session branch — deleting the branch
 * would strand them.
 */
unmergedCommits: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
