
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<Project[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions(projectId: string | null) : Promise<Result<Session[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessages(sessionPk: string) : Promise<Result<Message[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_messages", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectProject(workdir: string, name: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_project", { workdir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSession(projectId: string, prompt: string) : Promise<Result<Session, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_session", { projectId, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async continueSession(sessionPk: string, prompt: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_session", { sessionPk, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(requestId: string, allow: boolean) : Promise<boolean> {
    return await TAURI_INVOKE("resolve_approval", { requestId, allow });
},
async readFile(path: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickDirectory() : Promise<string | null> {
    return await TAURI_INVOKE("pick_directory");
},
async backdropCapability() : Promise<BackdropCapability> {
    return await TAURI_INVOKE("backdrop_capability");
},
async getSetting(key: string) : Promise<Result<string | null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProject(projectId: string, model: string | null, permMode: PermMode, harness: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project", { projectId, model, permMode, harness }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAgents() : Promise<Result<AgentInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-probe every catalog agent (PATH + --version + npm latest + local model
 * list for ollama), persist the snapshot, and return the fresh assembly.
 */
async refreshAgents() : Promise<Result<AgentInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAgent(id: string, enabled: boolean, model: string | null, permMode: string, flags: string) : Promise<Result<AgentInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent", { id, enabled, model, permMode, flags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAgentTier(id: string, tierId: string, value: string | null, combo: boolean) : Promise<Result<AgentInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_agent_tier", { id, tierId, value, combo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultAgent(id: string) : Promise<Result<AgentInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async systemAccentColor() : Promise<string | null> {
    return await TAURI_INVOKE("system_accent_color");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
accentChangedMsg: AccentChangedMsg,
coreEventMsg: CoreEventMsg
}>({
accentChangedMsg: "accent-changed-msg",
coreEventMsg: "core-event-msg"
})

/** user-defined constants **/



/** user-defined types **/

export type AccentChangedMsg = { hex: string }
export type AgentInfo = { id: string; name: string; color: string; initial: string; connection: string; binaryPath: string | null; installedVersion: string | null; latestVersion: string | null; npmPackage: string | null; models: string[]; enabled: boolean; model: string; permMode: string; flags: string; tiers: TierInfo[]; isDefault: boolean; 
/**
 * Whether Cockpit has a session harness for this agent today.
 */
runnable: boolean }
export type BackdropCapability = "mica" | "vibrancy" | "none"
export type CmdError = { message: string }
/**
 * Public event broadcast to consumers (the Tauri layer re-emits these).
 */
export type CoreEvent = { kind: "sessionCreated"; session_pk: string; project_id: string } | { kind: "message"; session_pk: string; seq: number; role: string; block_type: string; payload: JsonValue; tool_call_id: string | null; status: string | null; tool_kind: string | null } | { kind: "result"; session_pk: string } | { kind: "approvalRequested"; session_pk: string; request_id: string; tool: string; summary: string } | { kind: "error"; session_pk: string; message: string } | { kind: "sessionEnded"; session_pk: string }
export type CoreEventMsg = { event: CoreEvent }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * A persisted transcript entry. Forward-compatible with ACP session/update blocks.
 */
export type Message = { sessionPk: string; seq: number; role: string; blockType: string; payload: JsonValue; toolCallId: string | null; status: string | null; toolKind: string | null; createdAt: number }
export type PermMode = "default" | "acceptEdits" | "bypassPermissions" | "plan"
export type Project = { projectId: string; name: string; workdir: string; source: string | null; harness: string; model: string | null; effort: string | null; permMode: PermMode; createdAt: number | null }
export type Session = { sessionPk: string; projectId: string; agentSessionId: string | null; worktreePath: string | null; branch: string | null; title: string | null; status: SessionStatus; createdAt: number | null; lastActive: number | null }
export type SessionStatus = "idle" | "running" | "interrupted" | "ended"
export type TierInfo = { id: string; label: string; value: string | null; combo: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
