
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async listProjects() : Promise<Result<Project[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSessions(projectId: string | null) : Promise<Result<Session[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sessions", { projectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listMessages(sessionPk: string) : Promise<Result<Message[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_messages", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectProject(workdir: string, name: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_project", { workdir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSession(projectId: string, prompt: string) : Promise<Result<Session, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_session", { projectId, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async continueSession(sessionPk: string, prompt: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("continue_session", { sessionPk, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveApproval(requestId: string, allow: boolean) : Promise<boolean> {
    return await TAURI_INVOKE("resolve_approval", { requestId, allow });
},
async readFile(path: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickDirectory() : Promise<string | null> {
    return await TAURI_INVOKE("pick_directory");
},
async backdropCapability() : Promise<BackdropCapability> {
    return await TAURI_INVOKE("backdrop_capability");
},
async getSetting(key: string) : Promise<Result<string | null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSetting(key: string, value: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateProject(projectId: string, model: string | null, permMode: PermMode, harness: string) : Promise<Result<Project, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_project", { projectId, model, permMode, harness }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRuntimes() : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_runtimes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-probe every catalog agent (PATH + --version + npm latest + local model
 * list for ollama), persist the snapshot, and return the fresh assembly.
 */
async refreshRuntimes() : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_runtimes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRuntimeConfig(id: string, enabled: boolean, model: string | null, permMode: string, flags: string) : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_runtime_config", { id, enabled, model, permMode, flags }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fire-and-forget npm update; progress streams via CoreEvent
 * RuntimeUpdateLog / RuntimeUpdateDone, then a refreshed snapshot matters —
 * the UI calls refreshRuntimes() on Done.
 */
async updateRuntime(id: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_runtime", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRuntimeTier(id: string, tierId: string, value: string | null, combo: boolean) : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_runtime_tier", { id, tierId, value, combo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setDefaultRuntime(id: string) : Promise<Result<RuntimeInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_default_runtime", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runtimeConfigStatus(id: string) : Promise<Result<RuntimeConfigStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("runtime_config_status", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Guard (spec §5): refuse to write configs that point at a dead endpoint —
 * the server must be running and at least one endpoint key must exist.
 */
async applyRuntimeConfig(id: string, mapping: RuntimeMappingArg) : Promise<Result<RuntimeConfigStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_runtime_config", { id, mapping }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetRuntimeConfig(id: string) : Promise<Result<RuntimeConfigStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_runtime_config", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listGateways() : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_gateways") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Live probe: local telemetry, WSL detection, and SSH TCP reachability.
 */
async probeGateways() : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_gateways") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addGateway(name: string, host: string, port: number, username: string) : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_gateway", { name, host, port, username }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeGateway(id: string) : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_gateway", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateGateway(id: string, fsMode: string, paths: string[]) : Promise<Result<GatewayInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_gateway", { id, fsMode, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gatewayEvents(id: string) : Promise<Result<GatewayEventInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("gateway_events", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listJobs() : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_jobs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createJob(input: JobInput) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_job", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateJob(id: string, input: JobInput) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_job", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleJob(id: string, enabled: boolean) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_job", { id, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteJob(id: string) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_job", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runJobNow(id: string) : Promise<Result<JobInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_job_now", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Preview helper for the natural-language schedule editor.
 */
async parseNaturalSchedule(text: string) : Promise<string | null> {
    return await TAURI_INVOKE("parse_natural_schedule", { text });
},
async listApps() : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addApp(input: AddAppInput) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_app", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeApp(id: string) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_app", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async probeApp(id: string) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("probe_app", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateAppScope(id: string, scope: string, scopeGateways: string[]) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_scope", { id, scope, scopeGateways }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppToolPerm(id: string, tool: string, perm: string) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_tool_perm", { id, tool, perm }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleAppAgent(id: string, agentId: string, allowed: boolean) : Promise<Result<AppInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_app_agent", { id, agentId, allowed }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registrySearch(query: string | null, cursor: string | null) : Promise<Result<RegistryPage, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("registry_search", { query, cursor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listDir(sessionPk: string, rel: string) : Promise<Result<DirEntryInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dir", { sessionPk, rel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Absolute root path of the session's working tree (for opening files).
 */
async sessionWorkdir(sessionPk: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_workdir", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * What the session's OWN worktree would lose on teardown — the archive flow
 * asks before discarding either kind of work. Sessions whose worktree is
 * gone (or isn't a repo, e.g. an emptied leftover dir) report clean —
 * deliberately NOT the project-workdir fallback: the main checkout's state
 * is the user's business, not the session's.
 */
async worktreeDirty(sessionPk: string) : Promise<Result<WorktreeState, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("worktree_dirty", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitDiff(sessionPk: string) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_diff", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchFiles(projectId: string, query: string) : Promise<Result<string[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_files", { projectId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a shell in the session's worktree (or the project workdir).
 */
async termOpen(sessionPk: string, cols: number, rows: number) : Promise<Result<string, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_open", { sessionPk, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termInput(id: string, data: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_input", { id, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termResize(id: string, cols: number, rows: number) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_resize", { id, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async termClose(id: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_close", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kill every shell opened for a session — the archive/end flow runs this
 * BEFORE worktree teardown, or the shells' cwd handles block the directory
 * removal on Windows.
 */
async termCloseSession(sessionPk: string) : Promise<Result<null, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("term_close_session", { sessionPk }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async systemAccentColor() : Promise<string | null> {
    return await TAURI_INVOKE("system_accent_color");
},
async endpointStatus() : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("endpoint_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startEndpoint() : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_endpoint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopEndpoint() : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_endpoint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist port + autostart; restart the server when it was running.
 */
async setEndpointConfig(port: number, autostart: boolean) : Promise<Result<EndpointStatusInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_endpoint_config", { port, autostart }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listEndpointKeys() : Promise<Result<EndpointKeyInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_endpoint_keys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createEndpointKey(name: string) : Promise<Result<EndpointKeyInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_endpoint_key", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async revokeEndpointKey(id: string) : Promise<Result<EndpointKeyInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revoke_endpoint_key", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectionUsage(connectionId: string, days: number) : Promise<Result<UsageSeries, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connection_usage", { connectionId, days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endpointUsage(days: number) : Promise<Result<UsageSeries, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("endpoint_usage", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listProviderCatalog() : Promise<Result<CatalogEntry[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_provider_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConnections() : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addConnection(provider: string, label: string, apiKey: string, baseUrl: string | null) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_connection", { provider, label, apiKey, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateConnection(id: string, label: string, enabled: boolean, apiKey: string | null, baseUrl: string | null, models: string[]) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_connection", { id, label, enabled, apiKey, baseUrl, models }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeConnection(id: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveConnection(id: string, dir: number) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_connection", { id, dir }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Hit the upstream's model-list (openai) / a 1-token message (anthropic)
 * to distinguish bad key (401/403) from network trouble.
 */
async testConnection(id: string) : Promise<Result<TestResult, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drive the full interactive OAuth flow: binds a loopback listener, opens
 * the provider's authorize URL in the system browser via
 * `tauri-plugin-opener`, and awaits the callback (up to 5 minutes) before
 * persisting the resulting connection.
 */
async connectOauth(provider: string, label: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_oauth", { provider, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start the manual (paste) OAuth fallback for environments where the
 * loopback listener can't receive the provider's redirect: opens the
 * authorize URL and hands back the PKCE material so the UI can show a paste
 * field, completed later via [`complete_oauth_manual`].
 */
async beginOauthManual(provider: string) : Promise<Result<ManualStartInfo, CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("begin_oauth_manual", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async completeOauthManual(provider: string, label: string, verifier: string, state: string, pasted: string, redirectUri: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("complete_oauth_manual", { provider, label, verifier, state, pasted, redirectUri }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a `no_auth` connection for a Free-category provider — refuses any
 * other category (those need the api-key or OAuth flows above).
 */
async addFreeConnection(provider: string, label: string) : Promise<Result<ConnectionInfo[], CmdError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_free_connection", { provider, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
accentChangedMsg: AccentChangedMsg,
coreEventMsg: CoreEventMsg,
termExitMsg: TermExitMsg,
termOutputMsg: TermOutputMsg
}>({
accentChangedMsg: "accent-changed-msg",
coreEventMsg: "core-event-msg",
termExitMsg: "term-exit-msg",
termOutputMsg: "term-output-msg"
})

/** user-defined constants **/



/** user-defined types **/

export type AccentChangedMsg = { hex: string }
export type AddAppInput = { id: string | null; name: string; description: string; kind: string | null; 
/**
 * stdio | http
 */
transport: string; command: string | null; args: string[]; 
/**
 * KEY=VALUE pairs.
 */
env: string[]; url: string | null; version: string | null; publisher: string | null; color: string | null }
export type AgentAccessInfo = { agentId: string; allowed: boolean }
export type AppInfo = { id: string; name: string; kind: string; initial: string; color: string; desc: string; transport: string; command: string | null; args: string[]; url: string | null; scope: string; scopeGateways: string[]; status: string; statusDetail: string | null; version: string | null; publisher: string | null; authKind: string; authDetail: string | null; tools: ToolInfo[]; agentAccess: AgentAccessInfo[] }
export type BackdropCapability = "mica" | "vibrancy" | "none"
export type CatalogEntry = { id: string; name: string; color: string; initial: string; category: string; format: string; requiresBaseUrl: boolean; models: string[] }
export type CmdError = { message: string }
export type ConnectionInfo = { id: string; provider: string; providerName: string; color: string; initial: string; authType: string; label: string; priority: number; enabled: boolean; baseUrl: string | null; models: string[]; 
/**
 * e.g. "sk-…3fk9" — full key never leaves the backend after creation.
 */
keyMasked: string | null }
/**
 * Public event broadcast to consumers (the Tauri layer re-emits these).
 */
export type CoreEvent = { kind: "sessionCreated"; session_pk: string; project_id: string } | { kind: "message"; session_pk: string; seq: number; role: string; block_type: string; payload: JsonValue; tool_call_id: string | null; status: string | null; tool_kind: string | null } | { kind: "result"; session_pk: string } | { kind: "approvalRequested"; session_pk: string; request_id: string; tool: string; summary: string } | { kind: "error"; session_pk: string; message: string } | 
/**
 * Out-of-band announcement (e.g. "update available") rendered to every
 * surface of a session. TS parity: `{ kind: "notice", session_pk, text }`.
 */
{ kind: "notice"; session_pk: string; text: string } | { kind: "sessionEnded"; session_pk: string } | 
/**
 * A scheduled job run started or finished (status: running|success|failed).
 */
{ kind: "jobRunChanged"; job_id: string; run_id: string; status: string } | 
/**
 * A runtime npm install/update produced an output line.
 */
{ kind: "runtimeUpdateLog"; runtime_id: string; line: string } | 
/**
 * A runtime npm install/update finished (ok=false → message has detail).
 */
{ kind: "runtimeUpdateDone"; runtime_id: string; ok: boolean; message: string | null }
export type CoreEventMsg = { event: CoreEvent }
export type DirEntryInfo = { name: string; dir: boolean }
export type EndpointKeyInfo = { id: string; name: string; key: string; createdAt: number; lastUsedAt: number | null }
export type EndpointStatusInfo = { running: boolean; port: number; baseUrl: string; autostart: boolean }
export type GatewayEventInfo = { at: number; level: string; text: string }
export type GatewayInfo = { id: string; name: string; badge: string; 
/**
 * local | wsl | ssh
 */
kind: string; detail: string; metaLine: string; 
/**
 * connected | offline
 */
status: string; latency: string | null; daemonVersion: string; uptime: string | null; lastSeenMs: number | null; resources: GatewayResourceInfo[]; fingerprint: string | null; fsMode: string; paths: string[] }
export type GatewayResourceInfo = { label: string; sub: string; pct: number }
export type JobInfo = { id: string; name: string; cron: string; mode: string; natural: string; projectId: string; projectName: string; branch: string; agent: string; gateway: string; enabled: boolean; prompt: string; notifySuccess: boolean; notifyFail: boolean; nextRunMs: number | null; history: RunInfo[] }
export type JobInput = { name: string; mode: string; natural: string; cron: string; projectId: string; branch: string; agent: string; gateway: string; prompt: string; notifySuccess: boolean; notifyFail: boolean }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type ManualStartInfo = { authorizeUrl: string; verifier: string; state: string; redirectUri: string }
/**
 * A persisted transcript entry. Forward-compatible with ACP session/update blocks.
 */
export type Message = { sessionPk: string; seq: number; role: string; blockType: string; payload: JsonValue; toolCallId: string | null; status: string | null; toolKind: string | null; createdAt: number }
export type PermMode = "default" | "acceptEdits" | "bypassPermissions" | "plan"
export type Project = { projectId: string; name: string; workdir: string; source: string | null; harness: string; model: string | null; effort: string | null; permMode: PermMode; createdAt: number | null }
export type RegistryEntry = { 
/**
 * Registry name, e.g. `io.github.owner/server`.
 */
id: string; name: string; desc: string; version: string | null; publisher: string; 
/**
 * stdio (npm package) | http (remote)
 */
kind: string; 
/**
 * npm identifier for stdio entries; URL for remotes.
 */
installTarget: string | null; website: string | null }
export type RegistryPage = { entries: RegistryEntry[]; nextCursor: string | null }
export type RunInfo = { id: string; status: string; startedAtMs: number; durationMs: number | null; addLines: number | null; delLines: number | null; note: string | null; error: string | null; sessionPk: string | null }
export type RuntimeConfigStatusInfo = { configPath: string; exists: boolean; configured: boolean; 
/**
 * False for runtimes without an F1 handler (gemini, ollama).
 */
supported: boolean }
export type RuntimeInfo = { id: string; name: string; color: string; initial: string; connection: string; binaryPath: string | null; installedVersion: string | null; latestVersion: string | null; npmPackage: string | null; models: string[]; enabled: boolean; model: string; permMode: string; flags: string; tiers: TierInfo[]; isDefault: boolean; 
/**
 * Whether Cockpit has a session harness for this agent today.
 */
runnable: boolean }
export type RuntimeMappingArg = { model: string; opus: string | null; sonnet: string | null; haiku: string | null; models: string[] }
export type Session = { sessionPk: string; projectId: string; agentSessionId: string | null; worktreePath: string | null; branch: string | null; title: string | null; status: SessionStatus; startedBy: string | null; createdAt: number | null; lastActive: number | null; resumeAttempts: number }
export type SessionStatus = "idle" | "running" | "interrupted" | "ended"
export type TermExitMsg = { id: string }
export type TermOutputMsg = { id: string; 
/**
 * UTF-8 chunk (lossy) of PTY output.
 */
data: string }
export type TestResult = { ok: boolean; message: string }
export type TierInfo = { id: string; label: string; value: string | null; combo: boolean }
export type ToolInfo = { name: string; desc: string; perm: string }
export type UsagePoint = { day: string; requests: number; inputTokens: number; outputTokens: number }
export type UsageSeries = { days: UsagePoint[]; todayRequests: number; todayInputTokens: number; todayOutputTokens: number }
export type WorktreeState = { 
/**
 * Uncommitted work (staged, unstaged, or untracked).
 */
dirty: boolean; 
/**
 * Commits reachable only from the session branch — deleting the branch
 * would strand them.
 */
unmergedCommits: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
