//! Generated Wasmtime component-model host bindings for the `ryuzi:plugin`
//! world's host-provided imports (`host`, `settings`, `storage`,
//! `http`/`oauth`). Only `host`, `settings`, and `storage` are linked by this
//! slice — see `runtime.rs`'s `instantiate` for which `add_to_linker_instance`
//! calls are actually wired in, gated by [`super::super::runtime::HostPolicy`].
//!
//! Kept in its own file (rather than inlined in `mod.rs`) because
//! `wasmtime::component::bindgen!` output is large and is not meant to be
//! read/edited by hand.
//!
//! Generated module paths used elsewhere in `capabilities` (relative to this
//! module): `ryuzi::host::host`, `ryuzi::settings::settings`,
//! `ryuzi::storage::storage`, each exposing a `Host` trait, its
//! request/response record and error types, and `add_to_linker_instance`.
//! `add_to_linker_instance::<T, D>` requires `D: HasData` with
//! `for<'a> D::Data<'a>: Host` — the state type `T` itself is *not* the
//! `HasData` marker; `wasmtime::component::HasSelf<T>` is, and is what every
//! call site here passes as `D` (confirmed by direct probe, not assumed).

wasmtime::component::bindgen!({
    path: "../plugin-sdk/wit",
    world: "plugin",
});

/// Host bindings for the standalone `ryuzi:websocket@0.1.0` capability package.
///
/// Generated by a SECOND `bindgen!` (not the `plugin` world above) because
/// `ryuzi:websocket` is deliberately NOT imported by the root `ryuzi:plugin`
/// world — keeping that world (and every installed component's `wit-api`
/// range) byte-stable. The tiny host-only world below imports the interface so
/// wasmtime emits its `Host` trait + `add_to_linker_instance`; the interface
/// itself is still resolved from `../plugin-sdk/wit/deps/websocket.wit` (via
/// `path`), so that file stays the single source of truth. Reached elsewhere as
/// `websocket::ryuzi::websocket::websocket`.
pub mod websocket {
    wasmtime::component::bindgen!({
        inline: "
            package ryuzi:websocket-host@0.1.0;
            world websocket-host {
                import ryuzi:websocket/websocket@0.1.0;
            }
        ",
        path: "../plugin-sdk/wit",
        world: "websocket-host",
    });
}

/// Host bindings for the standalone `ryuzi:provider-auth@0.1.0` capability
/// package (Task 16c1).
///
/// Generated by its own `bindgen!` for exactly the reason `websocket` above is:
/// `ryuzi:provider-auth` is an ADDITIVE capability that the root `ryuzi:plugin`
/// world deliberately does not import, so that world — and therefore every
/// installed component's `wit-api` range — stays byte-stable and this is a
/// patch-level, ABI-compatible addition rather than a breaking world change.
/// The interface itself is still resolved from
/// `../plugin-sdk/wit/deps/provider-auth.wit` (via `path`), which stays the
/// single source of truth. Reached elsewhere as
/// `provider_auth::ryuzi::provider_auth::provider_auth`.
pub mod provider_auth {
    wasmtime::component::bindgen!({
        inline: "
            package ryuzi:provider-auth-host@0.1.0;
            world provider-auth-host {
                import ryuzi:provider-auth/provider-auth@0.1.0;
            }
        ",
        path: "../plugin-sdk/wit",
        world: "provider-auth-host",
    });
}
